var p2 = [
    { eng: 'ram te rahim teki sainath majhe', hin: 'राम ते रहीम तेची साईनाथ माझे', vol: '2', pn: '64' },
    { eng: 'kari tu bhajan pujn prabhu saike smaran', hin: 'करी तू भजन पूजन प्रभू साईचे स्मरण', vol: '2', pn: '65' },
    { eng: 'gauni to bal raju bhinicha', hin: 'गुणी तो बाळ राजू बहिणीचा', vol: '2', pn: '66' },
    { eng: 'majhya saike mandir te shirdit', hin: 'माझ्या साईचे मंदिर ते शिरडीत', vol: '2', pn: '67' },
    { eng: 'sainatha darshanasi anila parivar ho', hin: 'साईनाथा दर्शनासी आणिला परिवार हो', vol: '2', pn: '68' },
    { eng: 'sher shirdika sainatha putr pityavin ha', hin: 'शेर शिरडीचा साईनाथा पुत्र पित्याविण हा', vol: '2', pn: '69' },
    { eng: 'gunavanta dinnatha trivar vandan sainatha', hin: 'गुणवंता दीननाथा त्रिवार वंदन साईनाथा', vol: '2', pn: '70' },
    { eng: 'bhakt hi mandali shirdila chalali', hin: 'मक्त ही मंडळी शिरडीला चालली', vol: '2', pn: '71' },
    { eng: 'aika aika sasubai ho', hin: 'ऐका ऐका सासूबाई हो', vol: '2', pn: '72' },
    { eng: 'shirdi mandirat majhi vas kari ai', hin: 'शिरडी मंदिरात माझी वास करी आई', vol: '2', pn: '73' },
    { eng: 'aj bharalya darbarat alo tumachya mandirat', hin: 'आज भरल्या दरबारांत आलो तुमज्या मंदिरात', vol: '2', pn: '74' },
    { eng: 'anli taji khabar', hin: 'आणली ताजी खबर', vol: '2', pn: '75' },
    { eng: 'jagi koni kunacha na pranya', hin: 'जगी कोणी कुणाचा ना प्राण्या', vol: '2', pn: '76' },
    { eng: 'je tapulya dhani jivake', hin: 'जे ते अपुल्या धनी जीवाचे', vol: '2', pn: '77' },
    { eng: 'ai jhale mi sansarat', hin: 'आई झाले मी संसारात', vol: '2', pn: '78' },

    { eng: 'chala naranari ya ho sare miloni', hin: 'चला नरनारी या हो सारे मिळोनी', vol: '2', pn: '79' },
    { eng: 'bharale mam nayan prabhu bharale', hin: 'भरले मम नयन प्रभू भरले', vol: '2', pn: '80' },
    { eng: 'ti nako pandhari ti nako', hin: 'ती नको पंढरी ती नको', vol: '2', pn: '81' },
    { eng: 'sai kuthvar hi sai', hin: 'साई कुठवर ही साई', vol: '2', pn: '82' },
    { eng: 'dhany samadhi tya saiki', hin: 'धन्य समाधी त्या साईची', vol: '2', pn: '83' },
    { eng: 'nya jo majala tya shirdila', hin: 'न्या जो मजला त्या शिरडीला', vol: '2', pn: '84' },
    { eng: 'shirdila sai pragatle', hin: 'शिरडीला साई प्रगटले', vol: '2', pn: '85' },
    { eng: 'te sainatha majhe', hin: 'ते साईनाथा माझे', vol: '2', pn: '86' },
    { eng: 'sai tujha tya tya hrudayi vasale', hin: 'साई तुझा त्या त्या ह्रदयी वसले', vol: '2', pn: '87' },
    { eng: 'bhaja sainatha nahi kam dhanda', hin: 'भजा साईनाथा नाही काम धंदा', vol: '2', pn: '88' },
    { eng: 'sainam prabhunam sairam', hin: 'साईनाम प्रभुनाम साईराम', vol: '2', pn: '89' },
    { eng: 'bhar gheto jagacha tok raja', hin: 'भार घेतो जगाचा तोच राजा', vol: '2', pn: '90' },
    { eng: 'jivanat satyawanahi fasato', hin: 'जीवनात सत्यवानही फसतो', vol: '2', pn: '92' },
    { eng: 'paratun kadhi yar ho', hin: 'परतून कधी येणार हो', vol: '2', pn: '93' },
    { eng: 'jiv jaganyas ghabare', hin: 'जीव जगण्यास घाबरे', vol: '2', pn: '94' },
    { eng: 'aj anandi ranga bharala', hin: 'आज आनंदी रंग भरला', vol: '2', pn: '95' },
    { eng: 'ghya mukhane ghya ho prabhu', hin: 'घ्या मुखाने घ्या हो प्रभू', vol: '2', pn: '96' },
    { eng: 'pratyekane kra hatane', hin: 'प्रत्येकाने करा हाताने', vol: '2', pn: '98' },
    { eng: 'jhad chandnache lagale firaya', hin: 'झाड चदनाचे लागले फिराया', vol: '2', pn: '99' },
    { eng: 'mhapunyrashi tya jethe anant', hin: 'महापुण्यराशी त्या जेथे अनंत', vol: '2', pn: '100' },
    { eng: 'hati jholi alo gheuniya', hin: 'हाती झोळी आलो घेऊनिया', vol: '2', pn: '102' },
    { eng: 'dhagdhag agni jalto khali', hin: 'धगधग अग्नी जळतो खाली', vol: '2', pn: '103' },
    { eng: 'yaho chala arati karu', hin: 'याहो चला आरती करू', vol: '2', pn: '105' },

    { eng: 'amrutacha jhara gavasala', hin: 'अमृताचा झरा गवसला', vol: '2', pn: '107' },
    { eng: 'jo to manat vichar karato', hin: 'जो तो मनात विचार करतो', vol: '2', pn: '108' },
    { eng: 'sadgurus majhe magane ahe', hin: 'सदुगस माझे मागणे आहे', vol: '2', pn: '110' },
    { eng: 'devarayare kiti mi karave', hin: 'देवरायारे किती मी करावे', vol: '2', pn: '111' },
    { eng: 'shri hari re roj tujhachi re dhava', hin: 'श्री हरि रे रोज तुझाची रे धावा', vol: '2', pn: '112' },
    { eng: 'ya jivanat tu re bhagyechi labhalasi', hin: 'या जीवनात तू रे भाग्येची लाभलासी', vol: '2', pn: '113' },
    { eng: 'sadguru lila ti nyari marm bahu khol', hin: 'सदुगरू लीला ती न्यारी मर्म बहू खोल', vol: '2', pn: '115' },
    { eng: 'antrichya kala antari theviti', hin: 'अंतरीच्या कळा अंतरी ठेविती', vol: '2', pn: '117' },
    { eng: 'truptale n dole amuche kiti kiti pahu', hin: 'तृप्तले न डोढे आमुचे किती किती पाहू', vol: '2', pn: '119' },
    { eng: 'deva padar pasarite ashirvad', hin: 'देवा पदर पसरीते आशिर्वाद', vol: '2', pn: '120' },
    { eng: 'ghe mukhi roj bala prabhuchech', hin: 'घे मुखी रोज बाळा प्रभुचेच', vol: '2', pn: '121' },
    { eng: 'ha nashibi sansar deva', hin: 'हा नशिबी संसार देवा', vol: '2', pn: '122' },
    { eng: 'pajhar futato pashanala', hin: 'पाझर फुटतो पाषाणाला', vol: '2', pn: '123' },
    { eng: 'pandharit dang rangato abhang', hin: 'पंढरीत दंग रंगतो अभंग', vol: '2', pn: '2' },
    { eng: 'harine majala harishich dile', hin: 'हरिने मजला हरिशिच दिले', vol: '2', pn: '3' },
    { eng: 'kaik karati mani ha vichar', hin: 'कैक करती मनी हा विचार', vol: '2', pn: '4' },
    { eng: 'sampali shriguruchi bhramanti', hin: 'संपली श्रीगुरूची भ्रमंती', vol: '2', pn: '5' },
    { eng: 'sadguru dev chile tumhi jivani', hin: 'सदुगरू देव चिले तुम्ही जीवनी', vol: '2', pn: '6' },
    { eng: 'vatavrukshachya chhayekhali swanande', hin: 'वटवृक्षाच्या छायेखाली स्वानंदे', vol: '2', pn: '7' },
    { eng: 'dattarupi chile', hin: 'दत्तरूपी चिले', vol: '2', pn: '8' },
    { eng: 'ghe karuni uddhar', hin: 'घे करुनी उध्दार', vol: '2', pn: '9' },
    { eng: 'jhopale shri guru', hin: 'झोपले श्री गुरु', vol: '2', pn: '11' },
    { eng: 'karavirakar shankar dattachile', hin: 'करवीरकर शंकर दत्तचिले', vol: '2', pn: '12' },
    { eng: 'samadhimadhuni utha dattachile', hin: 'समाधीमधुनी उठा दत्तचिले', vol: '2', pn: '14' },
    { eng: 'nijabhaktache aikuni ghetil dhauni yetil', hin: 'निजभक्ताचे ऐकूनी घेतील धाऊनी येतील', vol: '2', pn: '15' },
    { eng: 'dattarajare chilayare lotu nako', hin: 'दत्तराजारे चिलयारे लोटू नको', vol: '2', pn: '16' },
    { eng: 'aga gururaya tujhe nam god', hin: 'अगा गुरूराया तुझे नाम गोड', vol: '2', pn: '17' },
    { eng: 'anantat ya anti lage na ant', hin: 'अनंतात या अंती लागे ना अंत', vol: '2', pn: '18' },
    { eng: 'shri gururaya dakhiv kimaya', hin: 'श्री गुरूराया दाखिव किमया', vol: '2', pn: '19' },
    { eng: 'om jay gurudev chile', hin: 'ॐ जय गुरूदेव चिले', vol: '2', pn: '20' },
    { eng: 'ganadhish tu ish tujala namito', hin: 'गणाधीश तूं ईश तुजला नमितो', vol: '2', pn: '21' },
    { eng: 'dongarakadyavara basale', hin: 'डोंगरकड्यावरा बसले', vol: '2', pn: '23' },
    { eng: 'na samadhani amuche jivan', hin: 'ना समाधानी अमुचे जीवन', vol: '2', pn: '24' },

    { eng: 'kshama kshama kari shri gururaya', hin: 'क्षमा क्षमा करी श्री गुरूराया', vol: '2', pn: '25' },
    { eng: 'ekamukhi dev rajadhiraj', hin: 'एकमुखी देव राजाधिराज', vol: '2', pn: '27' },
    { eng: 'sant jagati kaik swarupi', hin: 'संत जगती कैक स्वरूपी', vol: '2', pn: '28' },
    { eng: 'bahu divasachi bhaktajanachi', hin: 'बहू दिवसाची भक्तजनाची', vol: '2', pn: '29' },
    { eng: 'tula pahuniya hari pahiyela', hin: 'तुला पाहुनिया हरी पाहियेला', vol: '2', pn: '31' },
    { eng: 'harine majala harishich dile', hin: 'हरिने मजला हरिशिच दिले', vol: '2', pn: '32' },
    { eng: 'vatavrukshachya chhayekhali rahe gururaya', hin: 'वटवृक्षाच्या छायेखाली राहे गुरूराया', vol: '2', pn: '33' },
    { eng: 'geli nighuni vibhuti', hin: 'गेली निघूनी विभूती', vol: '2', pn: '34' },
    { eng: 'kon maranavari kon taran kari', hin: 'कोण मरणावरी कोण तारण करी', vol: '2', pn: '35' },
    { eng: 'gandh chandanacha majala avade', hin: 'गंध चंदनाचा मजला आवडे', vol: '2', pn: '36' },
    { eng: 'sadaiv jari tya bhagvantachya', hin: 'सदैव जरी लत्या भगवंताच्या', vol: '2', pn: '37' },
    { eng: 'dhanya jhalo amhi', hin: 'धन्य झालो आम्ही', vol: '2', pn: '38' },
    { eng: 'pancharati dharu hati', hin: 'पंचारती धरु हाती', vol: '2', pn: '39' },
    { eng: 'gharagharatun janamanatun nav ase', hin: 'घराघरातुन जनामनातून नाव असे', vol: '2', pn: '40' },
    { eng: 'anand anand anand vasudevanand', hin: 'आनंद आनंद आनंद वासुदेवानंद', vol: '2', pn: '41' },
    { eng: 'utha utha utha utha ho dattaraja vasudevanand', hin: 'उठा उठा उठा उठा हो दत्तराजा वासुदेवानंद', vol: '2', pn: '42' },
    { eng: 'tujhiya pujane bahujan tarale', hin: 'तुझिया पुजने बहुजन तरले', vol: '2', pn: '43' },
    { eng: 'maharashtratil sant janana', hin: 'महाराष्ट्रातील संत जनाना', vol: '2', pn: '44' },
    { eng: 'ati premane sthapan kele', hin: 'अति प्रेमाने स्थापन केले', vol: '2', pn: '45' },
    { eng: 'ghadi ghadi amha athavan hote', hin: 'घडी घडी आम्हा आठवण होते', vol: '2', pn: '48' },
    { eng: 'ati priy tu sarva devadikancha', hin: 'अथी प्रिय तू सर्व देवादिकांचा', vol: '2', pn: '49' },
    { eng: 'vruksh adnyaan tya dharativar dole', hin: 'वृक्ष अज्ञान त्या धरतीवर डोले', vol: '2', pn: '50' },
    { eng: 'brahm brahm om harihar sadguruchi', hin: 'ब्रम्ह ब्रम्ह ॐ हरिहर सद्गुरूची', vol: '2', pn: '51' },
    { eng: 'janakalyana ya dharativar jahale dattatray', hin: 'जनकल्याणा या धरतीवर जाहले दत्तात्रय', vol: '2', pn: '52' },
    { eng: 'hi punyabhumi sat purushanchi', hin: 'ही पूण्यभुमि सत पुरुषांची', vol: '2', pn: '53' },

    { eng: 'khara yogai dhund ish chintnat', hin: 'खरा योगी धुंद ईश चिंतनात', vol: '2', pn: '54' },
    { eng: 'sampali shrigurunchi bhramati', hin: 'संपली श्रुीगरूंची भ्रमती', vol: '2', pn: '55' },
    { eng: 'shripantachya athavaniche bhajan', hin: 'श्रीपंतच्या आठवणीचे भजन', vol: '2', pn: '56' },
    { eng: 'tya gaine bhar darbari', hin: 'त्या गाईने भर दरबारी', vol: '2', pn: '57' },
    { eng: 'jay dev jay dev jay bhalchandr', hin: 'जय देव जय देव जय भालचंद्र', vol: '2', pn: '58' },
    { eng: 'sampale sampanare jari sampale', hin: 'संपले सपणारे जरी संपल', vol: '2', pn: '59' },
    { eng: 'mrudunga vaje talavar tya', hin: 'मृदुंगा वाजे तालावर त्या', vol: '2', pn: '62' },
    { eng: 'mi vyaplo mi vyaplo', hin: 'मी व्यापलो मी व्यापलो', vol: '2', pn: '63' },
    { eng: 'dev majha bhav ahe', hin: 'देव माझा भाव आहे', vol: '2', pn: '124' },
    { eng: 'tujhya krupene jivan majhe krutarth', hin: 'तुझ्या कृपेने जीवन माझे कृतार्थ', vol: '2', pn: '125' },
    { eng: 'sajani halva hindola ala', hin: 'साजणी हालवा हिंदोळा आला', vol: '2', pn: '126' },
    { eng: 'nityam shubham mangalam', hin: 'नित्यम शुभम मंगलम', vol: '2', pn: '127' },
    { eng: 'nako chinta karu nako van van', hin: 'नको चिता करु नको वणवण', vol: '2', pn: '128' },
    { eng: 'chhaya ashich krupechi dhar', hin: 'छाया अशिच कृपेची धर', vol: '2', pn: '129' },
    { eng: 'nashibat lihile ase hoil', hin: 'नशिबात लिहिले असे होईल', vol: '2', pn: '131' },
    { eng: 'namaskar naman narayana', hin: 'नमस्कार नमन नारायणा', vol: '2', pn: '132' },
    { eng: 'shir namava tithe koni visaru', hin: 'शिर नमवा तिथे कोणी विसरु', vol: '2', pn: '133' },
    { eng: 'lagale maj ved ata shahana honar', hin: 'लागले मज वेड आता शाहणा होणार', vol: '2', pn: '134' },
    { eng: 'sadguru motha ase bhajatana deva', hin: 'सद्गुरू मोठा असे भजताना देवा', vol: '2', pn: '136' },
    { eng: 'charan guruche jethe pujiti', hin: 'चरण गुरूचे जेथे पूजिती', vol: '2', pn: '138' },

    { eng: 'kulachi pratistha tav hati', hin: 'कुळाची प्रतिष्टा तव हाती', vol: '2', pn: '140' },
    { eng: 'kadhi mi prapanchatuni dur jata', hin: 'कधी मी प्रपंचातुनी दूर जाता', vol: '2', pn: '141' },
    { eng: 'ya pudhil din tujhya sange javo', hin: 'या पुढील दिन तुझ्या संगे जावो', vol: '2', pn: '143' },
    { eng: 'ishwarachya mathi nanduya', hin: 'ईश्वराच्या मठी नांदुया', vol: '2', pn: '145' },
    { eng: 'shri gurudev yatiraj majhe', hin: 'श्री गुरूदेव यतीराज माझे', vol: '2', pn: '146' },
    { eng: 'kashala dila janm tehi kalena', hin: 'कशाला दिला जन्म तेही कळेना', vol: '2', pn: '147' },
    { eng: 'tujhe rup god tujhe nam', hin: 'तुझे रूप गोड तुझे नाम', vol: '2', pn: '149' },
    { eng: 'sangamacha thand vara rokhuni gheshil', hin: 'संगमाचा थंड वारा रोखुनि घेशिल', vol: '2', pn: '150' },
    { eng: 'sadguruchi manobhave seva ghado', hin: 'सद्गुरुची मनोभावे सेवा घडो', vol: '2', pn: '151' },
    { eng: 'jhunjato jivanbhar amhi prapanchasi', hin: 'झुंजतो जीवनभर आम्ही प्रपंचासी', vol: '2', pn: '152' },
    { eng: 'tuch bolka re deva', hin: 'तूच बोलका रे देवा', vol: '2', pn: '153' },
    { eng: 'hari har tu om namo sadguru', hin: 'हरी हर तू ॐ नमो सद्गुरु', vol: '2', pn: '154' },
    { eng: 'shraddha tujvari majhi purati', hin: 'श्रद्धा तुजवरी माझी पुरती', vol: '2', pn: '156' },
    { eng: 'tujvin ata jagave kase re', hin: 'तुजवीण आता जगावे कसे रे', vol: '2', pn: '157' },
    { eng: 'dev dinrat jagach ahe', hin: 'देव दिनरात जागाच आहे', vol: '2', pn: '158' },
    { eng: 'prabhu nam gheta smarita ananta', hin: 'प्रभू नाम घेता स्मरीता अनंता', vol: '2', pn: '160' },
    { eng: 'jay jay jay gurudev mauli', hin: 'जय जय जय गुरूदेव माउली', vol: '2', pn: '161' },
    { eng: 'sarvasvacha tyag karuni', hin: 'सर्वस्वाचा त्याग करुनी', vol: '2', pn: '162' },
    { eng: 'aga gururaya tujhe nam', hin: 'अगा गुरूराया तुझे नाम', vol: '2', pn: '163' },
    { eng: 'sansaracha bhar padti vichar', hin: 'संसाराचा भार पडती विचार', vol: '2', pn: '164' },
    { eng: 'sadguru shrihari chya vishranti', hin: 'सद्गुरु श्रीहरी च्या विश्रांती ', vol: '2', pn: '165' },
    { eng: 'guru maharaja tuj na visarale', hin: 'गुरु महाराजा तुज ना विसरले', vol: '2', pn: '166' },
    { eng: 'thor tujhe upkar deva', hin: 'थोर तुझे उपकार देवा', vol: '2', pn: '167' },
    { eng: 'jivanat nana prasangi jiv haka', hin: 'जीवनात नाना प्रसंगी जीव हाका', vol: '2', pn: '169' },
    { eng: 'jo jo bhakti ati sankate dhavati', hin: 'जो जो भक्ति अती संकटे धावती', vol: '2', pn: '170' },

    { eng: 'sampata yatra jivachi kirti rahe mage', hin: 'संपता यात्रा जीवाची किर्ती राहे मागे', vol: '2', pn: '171' },
    { eng: 'nako ant pahu nako dur rahu', hin: 'नको अंत पाहू नको दूर राहू', vol: '2', pn: '172' },
    { eng: 'aika sangato mi ata', hin: 'ऐका सांगतो मी आता', vol: '2', pn: '173' },
    { eng: 'to dhanychi jo tuj pahi', hin: 'तो धन्यची जो तुज पाही', vol: '2', pn: '174' },
    { eng: 'man dhauni jai gurukade', hin: 'मन धाऊनी जाई गुरूकडे', vol: '2', pn: '175' },
    { eng: 'tujvin gururaya gururaya', hin: 'तुजविण गुरूराया गुरूराया', vol: '2', pn: '176' },
    { eng: 'hi gardi hi murti he sthan', hin: 'ही गर्दी ही मूर्ती हे स्थान', vol: '2', pn: '177' },
    { eng: 'bhaktirasachya anant vata', hin: 'भक्तिरसाच्या अनंत वाटा', vol: '2', pn: '179' },
    { eng: 'parabramh paramatm devata', hin: 'परब्रम्ह परमात्म देवता', vol: '2', pn: '180' },
    { eng: 'deh patit ha darshanmatre', hin: 'देह पतित हा दर्शनमात्रे', vol: '2', pn: '182' },
    { eng: 'ka bare dur jashi', hin: 'का बरे दूर जाशी', vol: '2', pn: '183' },
    { eng: 'darshan ghadta harate bhan', hin: 'दर्शन घडता हरते भान', vol: '2', pn: '184' },
    { eng: 'dwar ughadi re gheuni alo', hin: 'द्वारा उघडी रे घेऊनी आलो', vol: '2', pn: '185' },
    { eng: 'sadguru davi yethe kimaya', hin: 'सदुगरू दावी येथे किमया', vol: '2', pn: '186' },
    { eng: 'tanman tujala arpan kele ya kudivar', hin: 'तनमन तुजला अर्पण केले या कुडीवर', vol: '2', pn: '189' },
    { eng: 'dur kadhi jau nako mala durun pahu', hin: 'दूर कधी जाऊ नको मला दुरून पाहू', vol: '2', pn: '191' },
    { eng: 'aga shriguru shiv tuj gun gato', hin: 'अगा श्रीगुरु शिव तुझे गुण गातो', vol: '2', pn: '192' },
    { eng: 'de darshan de prabhu re', hin: 'दे दर्शन दे प्रभू रे', vol: '2', pn: '193' },
    { eng: 'sharan sharan tuj shrigururaya', hin: 'शरण शरण तुज श्रुीगरूराया', vol: '2', pn: '194' },
    { eng: 'harale bhan kase n kale', hin: 'हरले भान कसे न कळे', vol: '2', pn: '195' },
    { eng: 'dattaraja ye tri savari savari', hin: 'दत्तराजा ये तरी सावरी सावरी', vol: '2', pn: '196' },
    { eng: 'tar anatha he bhagvanta', hin: 'तार अनाथा हे भगवंता', vol: '2', pn: '197' },
    { eng: 'yamini sampali mauli uthali', hin: 'यामिनी संपली माऊली उठली', vol: '2', pn: '199' },
    { eng: 'ya janmichya kartavyache amhi palan karanar', hin: 'या जन्मीच्या कर्तव्याचे आम्ही पालन करणार', vol: '2', pn: '200' },
    { eng: 'tujsathi bhajili bhakari', hin: 'तुजसाठी भाजिली भाकरी', vol: '2', pn: '201' },

    { eng: 'tujha sangatit maj rahu de re', hin: 'तुझा संगतीत मज राहू दे रे', vol: '2', pn: '202' },
    { eng: 'sadguru dirghayu ho de ashish re', hin: 'सद्गुरु र्दिघायु हो दे आशिष रे', vol: '2', pn: '203' },
    { eng: 'ha deh majha sadaiv jhijala', hin: 'हा देह माझा सदैव झिजला', vol: '2', pn: '204' },
    { eng: 'swami jato maghari', hin: 'स्वामी जातो माघारी', vol: '2', pn: '205' },
    { eng: 'dakhiv majala tujhi ti kimya', hin: 'दाखिव मजला तुझी ती किमया', vol: '2', pn: '206' },
    { eng: 'kakada sadguru pracha', hin: 'काकडा सद्गुरु प्रेमाचा', vol: '2', pn: '207' },
    { eng: 'ganagapurache amhi rahivashi', hin: 'गाणगापुराचे आम्ही रहिवाशी', vol: '2', pn: '208' },
    { eng: 'dev soniyacha dev pashanacha', hin: 'देव सोनियाचा देव पाषाणाचा', vol: '2', pn: '209' },
    { eng: 'ashtagandh laviyele shriguruchya bhali', hin: 'अष्टगंध लावियेले श्रुीगरूच्या भाळी', vol: '2', pn: '210' },
    { eng: 'nij man tujhuni durvar nahi', hin: 'निज मन तुजहुनी दुरवर नाही', vol: '2', pn: '211' },
    { eng: 'darshan ghado jiva ya', hin: 'दर्शन घडो जीवा या', vol: '2', pn: '213' },
    { eng: 'man dhave shriguruchya charani', hin: 'मन धावे श्रुीगुरूच्या चरणी', vol: '2', pn: '214' },
    { eng: 'dhir dharu kiti shriguru ata', hin: 'धीर धरु किती श्रुीगरू आता', vol: '2', pn: '215' },
    { eng: 'majha dev nij antari', hin: 'माझा देव निज अंतरी', vol: '2', pn: '217' },
    { eng: 'dya darshan sakla swamiji', hin: 'द्या दर्शन सकला स्वामिजी', vol: '2', pn: '218' },
    { eng: 'kadhihi fasavu nako vasra', hin: 'कधीही फसवू नको वासरा', vol: '2', pn: '219' },
    { eng: 'ya gharat ya gurudeva', hin: 'या घरात या गुरूदेवा', vol: '2', pn: '220' },
    { eng: 'jiv va tav rupacha', hin: 'जीव वेडा तव रूपाचा', vol: '2', pn: '221' },
    { eng: 'bhola majha bhav dev majha bhola', hin: 'भोळा माझा भाव देव माझा भोळा', vol: '2', pn: '222' },
    { eng: 'dev om datta majha', hin: 'देव ॐ दत्त माझा', vol: '2', pn: '223' },
    { eng: 'majala duje mandir na sapade', hin: 'मजला दुजे मंदिर ना सापडे', vol: '2', pn: '224' },
    { eng: 'he devaraya sharan tula re', hin: 'हे देवराया शरण तुला रे', vol: '2', pn: '226' },
    { eng: 'majala kadhi sodun jau nako', hin: 'मजला कधी सोडून जाऊ नको', vol: '2', pn: '227' },
    { eng: 'om parbramh paramatmane namah', hin: 'ॐ परब्रम्ह परमात्मने नमः ', vol: '2', pn: '228' },
    { eng: 'charandvay mi svaye pujiyele', hin: 'चरणद्वय मी स्वये पुजियेले', vol: '2', pn: '229' },

    { eng: 'deto tula dehdan', hin: 'देतो तुला देहदान', vol: '2', pn: '230' },
    { eng: 'tujhya vina ha jai jiv re', hin: 'तुझ्या विणा हा जाई जीव रे', vol: '2', pn: '231' },
    { eng: 'chalati shriguru te pathi', hin: 'चालती श्रुीगरू ते पथी', vol: '2', pn: '232' },
    { eng: 'ase kanti bhasmankit ti jyachi', hin: 'असे कांती भस्मांकित ती जयाची', vol: '2', pn: '233' },
    { eng: 'dnyaneshwara prtun ya bhuvari', hin: 'ज्ञानेश्ररा परतून या भूवरी', vol: '2', pn: '235' },
    { eng: 'kay apanat ahe sadguru', hin: 'काय आपणात आहे सद्गुरु', vol: '2', pn: '236' },
    { eng: 'bhakti kashi karu nakale', hin: 'भक्ति कशी करू नाकळे', vol: '2', pn: '237' },
    { eng: 'je have tujala magaun ghe', hin: 'जे हवे तुजला मगून घे', vol: '2', pn: '238' },
    { eng: 'jay jay he manohara', hin: 'जय जय हे मनोहरा', vol: '2', pn: '239' },
    { eng: 'maj ved lavi vithucha', hin: 'मज वेड लावी विठुचा', vol: '2', pn: '240' },
    { eng: 'akshay de vardan', hin: 'अक्षय दे वरदान', vol: '2', pn: '241' },
    { eng: 'he gururaya dakhiv thodi', hin: 'हे गुरूराया दाखिव थोडी', vol: '2', pn: '242' },
    { eng: 'vruksh audumbaracha jithe dise', hin: 'वृक्ष औदुम्बराचा जिथे दिसे', vol: '2', pn: '243' },
    { eng: 'ashadhicha sohala nighuni mi', hin: 'आषाढीचा सोहळा निघुनी मी', vol: '2', pn: '244' },
    { eng: 'kadhi tujhi ti pandhari pahu', hin: 'कधी तुझी ती पंढरी पाहू', vol: '2', pn: '245' },
    { eng: 'namadevane patr dhadile', hin: 'नामदेवाने पत्र धाडिले', vol: '2', pn: '246' },
    { eng: 'sharan sharan gurudev datta', hin: 'शरण् शरण गुरूदेव दत्ता', vol: '2', pn: '247' },
    { eng: 'andhar majhya jivani tohi dadun', hin: 'अंधार माझ्या जीवनी तोही दडून', vol: '2', pn: '248' },
    { eng: 'prarthana yati tujala bagh jiv', hin: 'प्रार्थना यति तुजला बघ जीव', vol: '2', pn: '249' },
    { eng: 'jado harinam lala manala', hin: 'जडो हरिनाम लळा मनाला', vol: '2', pn: '250' },
    { eng: 'karm dharm sare om datta narayan', hin: 'कर्म धर्म सारे ॐ दत्त नारायण', vol: '2', pn: '251' },
    { eng: 'lagbag de re darshan', hin: 'लगबग दे रे दर्शन', vol: '2', pn: '252' },
    { eng: 'jiavnachi dori lavachik bhara', hin: 'जीवनाची दोरी लवचिक भारा', vol: '2', pn: '254' },
    { eng: 'hya jivanat sukh dukhat tar', hin: 'ह्या जीवनात सुख दु : खात तार', vol: '2', pn: '255' },
    { eng: 'he usthiladhipti tujala mam', hin: 'हे उस्थिलाधिपती तुजला मम', vol: '2', pn: '256' },

    { eng: 'bhoga bhoganyala shakti milel', hin: 'भोग भोगण्याला शक्ति मिळेल', vol: '2', pn: '257' },
    { eng: 'tujvin ata jagave kase re', hin: 'तुजवीण आता जगावे कसे रे', vol: '2', pn: '258' },
    { eng: 'asha purvi janyapurvi', hin: 'आशा पुरवी जाण्यापूर्वी', vol: '2', pn: '259' },
    { eng: 'jya charanache sparshit jal te', hin: 'ज्या चरणाचे स्पर्शित जल ते', vol: '2', pn: '260' },
    { eng: 'chaitnyacha theva majha gurudev', hin: 'चैतन्याचा ठेवा माझा गुरूदेव', vol: '2', pn: '261' },
    { eng: 'sansar bandivas bhakticha lage', hin: 'संसार बंदीवास भक्तिचा लागे', vol: '2', pn: '262' },
    { eng: 'payi khadava ghala guruvar', hin: 'पायी खडावा घाला गुरूवर', vol: '2', pn: '263' },
    { eng: 'he shriguru adi guru', hin: 'हे श्रुीगरू आदि गुरु', vol: '2', pn: '264' },
    { eng: 'deva kuthe rahashi', hin: 'देवा कुठे राहशी', vol: '2', pn: '265' },
    { eng: 'karunakara karuneshrvara', hin: 'करुणाकरा करूणेश्र्वरा', vol: '2', pn: '266' },
    { eng: 'hech sthan hich bhumi', hin: 'हेच स्थान हिच भूमी', vol: '2', pn: '267' },
    { eng: 'he prabhu re prabhu re majhi', hin: 'हे प्रभू रे प्रभू रे माझी', vol: '2', pn: '268' },
    { eng: 'mi tar tujhech lekaru', hin: 'मी तर तुझेच लेकरु', vol: '2', pn: '269' },
    { eng: 'keli vari alo dari', hin: 'केली वारी आलो दारी', vol: '2', pn: '270' },
    { eng: 'he usthiladhipti raja khel', hin: 'हे उस्थिलाधिपती राजा खेळ', vol: '2', pn: '271' },
    { eng: 'he mam bhagvanta far vilamb', hin: 'हे मम भगवंता फार विलंब', vol: '2', pn: '272' },
    { eng: 'chuko na kadhi te kartavy', hin: 'चुको ना कधी ते कर्तव्य', vol: '2', pn: '273' },
    { eng: 'jalabhitari tya shripadraje', hin: 'जलाभितरी त्या श्रीपादराजे', vol: '2', pn: '274' },
    { eng: 'panchgange kathavarti kiti vat', hin: 'पंचगंगे काठावरती किती वाट', vol: '2', pn: '275' },
    { eng: 'bare paduranga bhoga bhogu de', hin: 'बारे पाडुरंगा भोग भूोगु दे', vol: '2', pn: '276' },
    { eng: 'dhavare pav re dhav re gururaya', hin: 'धावरे पाव रे धाव रे गुरूराया', vol: '2', pn: '277' },
    { eng: 'apradhachi kshama asavi pudhalya', hin: 'अपराधाची क्षमा असावी पुढल्या', vol: '2', pn: '278' },
    { eng: 'bramh harihar ka lapalase', hin: 'ब्रम्ह हरिहर का लपलासे', vol: '2', pn: '279' },
    { eng: 'ithuni pudhle je ghadne te changalechi', hin: 'इथुनी पुढले जे घडणे ते चांगलेची', vol: '2', pn: '280' },
    { eng: 'pragat re pragat re pragat shrigururaya', hin: 'प्रगट रे प्रगट रे प्रगट श्रुीगुरूराया', vol: '2', pn: '281' },

    { eng: 'pranay namah pranaday namah', hin: 'प्राणाय नम: प्राणदाय नम:', vol: '2', pn: '282' },
    { eng: 'onjalit kadhi tari mi', hin: 'ओंजळीत कधी तरी मी', vol: '2', pn: '284' },
    { eng: 'tujvar shraddha majhi purati', hin: 'तुजवर श्रद्धा माझी पुरती', vol: '2', pn: '285' },
    { eng: 'tujhi jethe marji tithe jiv', hin: 'तुझी जेथे मर्जी तिथे जीव', vol: '2', pn: '286' },
    { eng: 'majhi bhakti milte ka re', hin: 'माझी भक्ति मिळते का रे', vol: '2', pn: '287' },
    { eng: 'kela punit sparshe yativarni', hin: 'केला पुनित स्पर्शे यतिवरनी', vol: '2', pn: '288' },
    { eng: 'prabhunamat man raho dang', hin: 'प्रभूनामात मन राहो दंग', vol: '2', pn: '289' },
    { eng: 'anant janmache apradhi jivani', hin: 'अनंत जन्माचे अपराधी जीवनी', vol: '2', pn: '290' },
    { eng: 'he akhil vishv parameshwaray', hin: 'हे अखिल विश्व परमेश्वराय', vol: '2', pn: '294' },
    { eng: 'kadhi kadhi deva majha ur', hin: 'कधी कधी देवा माझा ऊर', vol: '2', pn: '295' },
    { eng: 'janmojanmicha ha jiv jahala', hin: 'जन्मोजन्मीचा हा जीव जाहला', vol: '2', pn: '297' },
    { eng: 'majha tochi gav jithe gheto dhav', hin: 'माझा तोची गाव जिथे घेतो धाव', vol: '2', pn: '298' },
    { eng: 'devani re savari savari', hin: 'देवानी रे सावरी सावरी', vol: '2', pn: '299' },
    { eng: 'theu nako paradhin he majhe', hin: 'ठेऊ नको पराधीन हे माझे', vol: '2', pn: '300' },
    { eng: 'he jagadish kartavyachi dakhiv', hin: 'हे जगदीश कर्तव्याची दाखिव', vol: '2', pn: '301' },
    { eng: 'gururaya tujhech mi lekaru', hin: 'गुरूराया तुझेच मी लेकरु', vol: '2', pn: '302' },
    { eng: 'gau nako re majhi kirti', hin: 'गाऊ नको रे माझी किर्ती', vol: '2', pn: '303' },
    { eng: 'dosh deshi ka davala dev', hin: 'दोष देशी का देवाला देव', vol: '2', pn: '304' },
    { eng: 'jivabhavach daivat majh nivas', hin: 'जीवाभावाच दैवत माझ निवास', vol: '2', pn: '305' },
    { eng: 'janmpudhala jo tithe na uru de', hin: 'जन्मपुढला जो तिथे ना ऊरू दे', vol: '2', pn: '306' },
    { eng: 'kadhi tari tu prasann houn', hin: 'कधी तरी तू प्रसन्न होऊन', vol: '2', pn: '307' },
    { eng: 'he akhilvishv parameshwara rangarup', hin: 'हे अखिलविश्व परमेश्वरा रंगरूप', vol: '2', pn: '308' },
    { eng: 'man ghadi ghadi vade hri', hin: 'मन घडी घडी वदे हरि', vol: '2', pn: '309' },
    { eng: 'tujhiya krupene mangal hovo', hin: 'तुझिया कृपेने मंगल होवो', vol: '2', pn: '310' },
    { eng: 'ka re ajuni dislas na', hin: 'का रे अजूनी दिसलास ना', vol: '2', pn: '311' },

    { eng: 'kshanbhar ye pandurnga', hin: 'क्षणभर ये पांडुरंगा', vol: '2', pn: '312' },
    { eng: 'jivanat bhale sukh dukh aso', hin: 'जीवनात भले सुखदुख असो', vol: '2', pn: '313' },
    { eng: 'sharanagati savari hank aikun', hin: 'शरणागती सावरी हाक ऐकून', vol: '2', pn: '314' },
    { eng: 'tu antardnyani janshi man', hin: 'तू अंतरज्ञानी जाणशी मन', vol: '2', pn: '315' },
    { eng: 'kshanbhar ye re keshva madhava', hin: 'क्षणभर ये रे केशवा माधवा', vol: '2', pn: '316' },
    { eng: 'bhajan puajan tujhe smaadhan', hin: 'भजन पूजन तुझे समाधान', vol: '2', pn: '317' },
    { eng: 'kshama kari tu vilamb jahla', hin: 'क्षमा करी तू विलंब जाहला', vol: '2', pn: '318' },
    { eng: 'shri guru majahuni duri naso', hin: 'श्रीगुरु मजहुनी दुरी नसो', vol: '2', pn: '320' },
    { eng: 'de varadan de varadan vithu', hin: 'दे वरदान दे वरदान विठू', vol: '2', pn: '321' },
    { eng: 'kartavy majhe ya janmiche nirdosh', hin: 'कर्तव्य माझे या जन्मीचे निर्दोष', vol: '2', pn: '322' },
    { eng: 'magane majhe swalp ase re', hin: 'मागणे माझे स्वल्प असे रे', vol: '2', pn: '323' },
    { eng: 'to badashahi that mala re', hin: 'तो बादाशाही थाट मला रे', vol: '2', pn: '324' },
    { eng: 'sangam tiri ghar yatirajache', hin: 'संगम तीरी घर यतीराजाचे', vol: '2', pn: '326' },
    { eng: 'tujhi rahem najar ya jivavar', hin: 'तुझी रहेमनजर या जीवावर', vol: '2', pn: '327' },
    { eng: 'jayjay jayjay bhu garbh', hin: 'जयजय जयजय भू गर्भ', vol: '2', pn: '328' },
    { eng: 'madhava va namacha ha jiv', hin: 'माधवा वेडा नामाचा हा जीव', vol: '2', pn: '329' },
    { eng: 'he prabhu re tujhech chintan dhyan', hin: 'हे प्रभू रे तुझेच चिंतन ध्यान', vol: '2', pn: '330' },
    { eng: 'savar tu datta ananta', hin: 'सावर तू दत्ता अनंता', vol: '2', pn: '331' },
    { eng: 'he vishwa uddharka tujhyach savar', hin: 'हे विश्वउध्दारका तुझ्याच सावर', vol: '2', pn: '332' },
    { eng: 'lagala maj chhand mand sugandh god', hin: 'लागला मज छंद मंद सुगंध गोड', vol: '2', pn: '333' },
    { eng: 'krupa hast tu dharshil ka', hin: 'कृपा हस्त तू धरशिल का', vol: '2', pn: '334' },
    { eng: 'he gururaya dhar parachhai', hin: 'हे गुरुराया धर परछाई', vol: '2', pn: '335' },
    { eng: 'gokul jhale majhe ghar', hin: 'गोकुळ झाले माझे घर', vol: '2', pn: '336' },
    { eng: 'mi tujhach lek tuch majha bap', hin: 'मी तुझाच लेक तुच माझा बाप', vol: '2', pn: '337' },
    { eng: 'de dnyan aise je nirdos ahe', hin: 'दे ज्ञान ऐसे जे निर्दोष आहे', vol: '2', pn: '338' },
    { eng: 'dhav pav ughadi dwar nayni rup', hin: 'धाव पाव उघडी द्वार नयनी रूप', vol: '2', pn: '339' },

    { eng: 'agala ahe jivan sindhu', hin: 'आगळा आहे जीवन सिँधू', vol: '2', pn: '340' },
    { eng: 'kadhi majala antar deu nako', hin: 'कधी मजला अंतर देऊ नको', vol: '2', pn: '341' },
    { eng: 'tujhe swarup dekhne pasant majala', hin: 'तुझे स्वरूप देखणे पसंत मजला', vol: '2', pn: '342' },
    { eng: 'he kartavyadhikari daivata vandan', hin: 'हे कर्तव्याधिकारी दैवता वंदन', vol: '2', pn: '343' },
    { eng: 'nahi kadhi nahi karnar mi', hin: 'नाही कधी नाही करणार मी', vol: '2', pn: '344' },
    { eng: 'de dnyan mala ituke jiv ha tujhech', hin: 'दे ज्ञान मला इतुके जीव हा तुझेच', vol: '2', pn: '345' },
    { eng: 'kalpnene mam hrudayat mandir te', hin: 'कल्पनेने मम हृदयात मंदिर ते', vol: '2', pn: '346' },
    { eng: 'dan deta dayaluch dineshvar', hin: 'दान देता दयाळूच दीनेश्वर', vol: '2', pn: '347' },
    { eng: 'sanmargi he paul valo', hin: 'सन्मार्गी हे पाऊल वळो', vol: '2', pn: '348' },
    { eng: 'tav bhaktashi dirghayu de', hin: 'तव भक्ताशी र्दिघायु दे', vol: '2', pn: '349' },
    { eng: 'prabhu ramchandra tujhi krupa kar', hin: 'प्रभूरामचँद्रा तुझी कृपा कर', vol: '2', pn: '350' },
    { eng: 'rachilis pruthvi kaisi nach dise', hin: 'रचिलीस पृथ्वी कैसी नच दिसे', vol: '2', pn: '351' },
    { eng: 'darshan tujhe te ghado daridry amuche', hin: 'दर्शन तुझे ते घडो दारिद्रय आमुचे', vol: '2', pn: '352' },
    { eng: 'talcharan majhe ata jhijale', hin: 'तळचरण माझे आता झिजले', vol: '2', pn: '353' },
    { eng: 'hanumanta thayi joda bhaktinate', hin: 'हनुमंता ठायी जोडा भक्तिनाते', vol: '2', pn: '355' },
    { eng: 'narayana re maj huni duri', hin: 'नारायणा रे मज हुनी दूरी', vol: '2', pn: '356' },
    { eng: 'tujhe pandurnga nam god', hin: 'तुझे पांडुरंग नाम गोड', vol: '2', pn: '357' },
    { eng: 'he ananta ant tujha na', hin: 'हे अनता अंत तुझा ना', vol: '2', pn: '358' },
    { eng: 'narayanare sthavar jangam rup', hin: 'नारायणारे स्थावर जंगम रूप', vol: '2', pn: '359' },
    { eng: 'dene asel darshan tar de', hin: 'देणे असेल दर्शन तर दे', vol: '2', pn: '360' },
    { eng: 'de guru de guru darshan', hin: 'दे गुरु दे गुरु दर्शन', vol: '2', pn: '361' },
    { eng: 'hovo majhya mathi namacha', hin: 'होवो माझ्या माथी नामाचा', vol: '2', pn: '362' },
    { eng: 'pakharu te pankhakhali ghetse', hin: 'पाखरू ते पंखाखाली घेतसे', vol: '2', pn: '363' },
    { eng: 'chuk mul hi chya padari', hin: 'चूक मूल ही च्या पदरी', vol: '2', pn: '364' },
    { eng: 'he bhagvanta narsimhnatha', hin: 'हे भगवंता नृसिंहनाथा', vol: '2', pn: '366' },

    { eng: 'sadgurunatha vinavito ata', hin: 'सदुगुरूनाथा विनवितो आता', vol: '2', pn: '367' },
    { eng: 'thave n udyache aj mala', hin: 'ठावे न उद्याचे आज मला', vol: '2', pn: '368' },
    { eng: 'tujhi jethe marji mi tyachyat raji', hin: 'तुझी जेथे मर्जी मी त्याच्यात राजी', vol: '2', pn: '370' },
    { eng: 'janm pudhcha mala milel tujhiya', hin: 'जन्म पुढचा मला मिळेल तुझिया', vol: '2', pn: '372' },
    { eng: 'tujhya sngatit majhe sampu de he jivan', hin: 'तुझ्या संगतीत माझे संपू दे हे जीवन', vol: '2', pn: '373' },
    { eng: 'sukhe nav hi pailtiras nyavi', hin: 'सुखे नाव ही पैलतीरास न्यावी', vol: '2', pn: '374' },
    { eng: 'kay kona mani sarv thave', hin: 'काय कोणा मनी सर्व ठावे', vol: '2', pn: '375' },
    { eng: 'gango tu li bhola deva', hin: 'गांगो तू लई भोळा देवा', vol: '2', pn: '376' },
    { eng: 'paratuni janmlo tar privar ha nako', hin: 'परतुनी जन्मलो तर परिवार हा नको', vol: '2', pn: '377' },
    { eng: 'rahun rahun ghadi ghadi yeti', hin: 'राहून राहून घडी घडी येती', vol: '2', pn: '378' },
    { eng: 'donach din te vastavyache dattai', hin: 'दोनच दिन ते वास्तव्याचे दत्ताई', vol: '2', pn: '379' },
    { eng: 'jashil kare sandesh nere', hin: 'जाशिल कारे संदेश नेरे', vol: '2', pn: '380' },
    { eng: 'hi tujhyakade jai jari vat', hin: 'ही तुझ्याकडे जाई जरी वाट', vol: '2', pn: '382' },
    { eng: 'majhe apure mi duje pahu kashala', hin: 'माझे अपुरे मी दुजे पाहू कशाला', vol: '2', pn: '384' },
    { eng: 'virajman jethe shriguru', hin: 'विराजमान जेथे श्रुीगरू', vol: '2', pn: '386' },
    { eng: 'mi tr tujhech lekaru', hin: 'मी तर तुझेच लेकरू', vol: '2', pn: '387' },
    { eng: 'tan man dhan tyat bhagvant', hin: 'तन मन धन त्यात भगवंत', vol: '2', pn: '388' },
    { eng: 'jhad veli mhanati prabhula de', hin: 'झाड वेली म्हणती प्रभूला दे', vol: '2', pn: '389' },
    { eng: 'ghardhani jumpa gadila jodi', hin: 'घरधनी जुंपा गाडीला जोडी', vol: '2', pn: '390' },
    { eng: 'kiti kal ga mala janmuniya', hin: 'किती काळ गेला मला जन्मूनिया', vol: '2', pn: '392' },
    { eng: 'janm ghetalase ya janmi uddharu', hin: 'जन्म घेतलासे या जन्मी उध्दरू', vol: '2', pn: '393' },
    { eng: 'shri gurucharitra kavy', hin: 'श्रीगुरुचरित्र काव्य', vol: '2', pn: '394' },
    { eng: 'ramkrushn hari namo narayan', hin: 'रामकृष्ण हरि नमो नारायण', vol: '2', pn: '402' },
    { eng: 'sajari gurupaurnima saksh deto nabhi chandrama', hin: 'साजरी गुरूपौर्णिमा साक्ष देतो नभी चंद्रमा', vol: '2', pn: '403' },
    { eng: 'nimm lile apar madi nann jivan', hin: 'निम्म लीले अपार माडी नन्न जीवन', vol: '2', pn: '404' },
    { eng: 'ramkrushn hari ramkrushn hari', hin: 'रामकृष्ण हरी रामकृष्ण हरी', vol: '2', pn: '405' },
    { eng: 'jay raghunandan brahmaharihar gananayakaji', hin: 'जय रघुनंदन ब्र्म्हहरिहर गणनायकजी', vol: '2', pn: '406' }
];
