var p4 = [
    { eng: 'kay sangu majhya bharatarala', hin: 'काय सांगु माझ्य भरतारला', vol: '4', pn: '3' },
    { eng: 'hya daryachya latevri', hin: 'ह्या दर्याच्या लाटेवरी', vol: '4', pn: '4' },
    { eng: 'tujhya marjin sansar karu', hin: 'तुझ्या मर्जीन संसार करू', vol: '4', pn: '5' },
    { eng: 'jgavala ha kasa navara', hin: 'जगावेगळा हा कसा नवरा', vol: '4', pn: '6' },
    { eng: 'madhusudana giridhar he mohana', hin: 'मधुसुदना गिरिधर हे मोहना', vol: '4', pn: '7' },
    { eng: 'paule chalali pandhari vat', hin: 'पाऊले चालली पंढरी वाट', vol: '4', pn: '8' },
    { eng: 'ghei dhav vedya vithu darshanala', hin: 'घेई धाव वेड्या विठू दर्शनाला', vol: '4', pn: '9' },
    { eng: 'bhalas lav tikli', hin: 'भाळास लाव टिकली', vol: '4', pn: '10' },
    { eng: 'pahuni poricha chala', hin: 'पाहुनी पोरीचा चाळा', vol: '4', pn: '11' },
    { eng: 'he nara kar jarasa vichar', hin: 'हे नरा कर जरासा विचार', vol: '4', pn: '12' },
    { eng: 'o mirachivali tikhat mirachi', hin: 'ओ मिरचीवाली तिखट मिरची', vol: '4', pn: '15' },
    { eng: 'ramalkas vedya adhi sansarat', hin: 'रमल्कास वेड्या आधी संसारात', vol: '4', pn: '16' },
    { eng: 'kamal jhali langoti geli', hin: 'कमाल झाली लंगोटी गेली', vol: '4', pn: '17' },
    { eng: 'bagh madi ti vadi', hin: 'बघ माडी ती वाडी', vol: '4', pn: '18' },
    { eng: 'gheuni janm bhuvari mi re', hin: 'घेऊनी जन्म भूवरी मी रे', vol: '4', pn: '19' },
    { eng: 'he ganraya bhavbhay harana', hin: 'हे, गणराया भवभय हरणा', vol: '4', pn: '20' },
    { eng: 'sansaracha bhar bhovati', hin: 'संसाराचा भार भोवती', vol: '4', pn: '21' },
    { eng: 'athava kshanabhar bhimaichya jivanavr', hin: 'आठवा क्षणभर भिमाईच्या जीवनावर', vol: '4', pn: '22' },
    { eng: 'jani mhane nama rungu de abhanga', hin: 'जनी म्हणे नामा रूंगु दे अभंग', vol: '4', pn: '23' },
    { eng: 'jhalas majori', hin: 'झालास माजोरी', vol: '4', pn: '24' },
    { eng: 'ram karo khel', hin: 'राम करो खेळ', vol: '4', pn: '25' },
    { eng: 'ghado sakala te darshan', hin: 'घडो सकला, ते दर्शन', vol: '4', pn: '26' },
    { eng: 'bdnam jahlas tu', hin: 'बदनाम जाहलास तू', vol: '4', pn: '27' },
    { eng: 'sambhal tu pora', hin: 'साम्भाळ तू पोरा', vol: '4', pn: '28' },

    { eng: 'ata sasarchya jate ghara', hin: 'आता सासरच्या जाते घरा', vol: '4', pn: '29' },
    { eng: 'chal ge sakhe pandharila', hin: 'चल गे सखे पंढरीला', vol: '4', pn: '30' },
    { eng: 'karm tujhe tu chuku nako', hin: 'कर्म तुझे तु चुकू नको', vol: '4', pn: '31' },
    { eng: 'jivacha sakha tu sakha panduranga', hin: 'जीवाचा सखा तू सखा पांडुरंग', vol: '4', pn: '33' },
    { eng: 'dev tu janacha', hin: 'देव तू जनाचा', vol: '4', pn: '34' },
    { eng: 'thor kara balano kam', hin: 'थोर करा बाळानो काम', vol: '4', pn: '35' },
    { eng: 'mi arpan karta pauli', hin: 'मी अर्पण करता पाऊली', vol: '4', pn: '36' },
    { eng: 'to kon ho', hin: 'तो कोण हो ?', vol: '4', pn: '37' },
    { eng: 'athvita kharokhar he kalij ture', hin: 'आठविताँ खरोखर हे काळिज तुरे', vol: '4', pn: '39' },
    { eng: 'javaibapu ghusnar', hin: 'जावईबापू घुसणार', vol: '4', pn: '41' },
    { eng: 'sadla ka kan karndaivi', hin: 'सडला का कण कर्णदैवी', vol: '4', pn: '42' },
    { eng: 'pora na tu re sadhabhola', hin: 'पोरा ना तुं रे साधाभोळा', vol: '4', pn: '44' },
    { eng: 'tuj trivar vandan bhagvanta', hin: 'तुज त्रिवार वंदन भगवंता', vol: '4', pn: '45' },
    { eng: 'chandrabhage par tya dayechi dhar', hin: 'चंद्रभागे पार- त्या दयेची धार', vol: '4', pn: '46' },
    { eng: 'chhaya mile krupechi', hin: 'छाया मिळे कृपेची', vol: '4', pn: '47' },
    { eng: 'tujha mandirat smadhi sajvili', hin: 'तुझा मंदिरात समाधी सजविली', vol: '4', pn: '48' },
    { eng: 'lakshmi ithe ratr din vase', hin: 'लक्ष्मी इथे रात्र दिन वसे', vol: '4', pn: '49' },
    { eng: 'mujara aj sari', hin: 'मुजरा आज सारी', vol: '4', pn: '50' },
    { eng: 'dharu naka adhi', hin: 'धरू नका आढी', vol: '4', pn: '51' },
    { eng: 'hi dhadpad karto', hin: 'ही धडपड करतो', vol: '4', pn: '52' },
    { eng: 'ja chora din bharle ja', hin: 'जा चोरा दिन भरले जा', vol: '4', pn: '53' },
    { eng: 'jare jare pure kar radgane', hin: 'जारे जारे पुरे कर रडगाणे', vol: '4', pn: '54' },
    { eng: 'kamal polisanchi', hin: 'कमाल पोलिसांची', vol: '4', pn: '55' },
    { eng: 'bhari jhali ti', hin: 'भारी झाली ती', vol: '4', pn: '56' },
    { eng: 'sodin donhi bailana', hin: 'सोडीन दोन्ही बैलाना', vol: '4', pn: '57' },
    { eng: 'svargichya prabhu', hin: 'स्वर्गीच्या प्रभू', vol: '4', pn: '59' },
    { eng: 'thamb jra re kora', hin: 'थांब जरा रे चोरा', vol: '4', pn: '60' },

    { eng: 'adhi pandharicha', hin: 'आधी पंढरीचा', vol: '4', pn: '61' },
    { eng: 'tej lochanat hat', hin: 'तेज लोचनात हात', vol: '4', pn: '62' },
    { eng: 'bhushana he raghukul', hin: 'भुषणा हे रघुकुळ', vol: '4', pn: '63' },
    { eng: 'jara athavi bhaktigit re', hin: 'जरा आठवी भक्तिगीत रे', vol: '4', pn: '64' },
    { eng: 'majhiya sadni gurusvami', hin: 'माझिया सदनी गुरूस्वामी', vol: '4', pn: '65' },
    { eng: 'aj kolivaryat', hin: 'आज कोलिवार्यात', vol: '4', pn: '66' },
    { eng: 'tu dipak mi tujhi bhavana', hin: 'तू दिपक मी तुझी भावना', vol: '4', pn: '67' },
    { eng: 'kadhi tithe najar', hin: 'कधी तिथे नजर', vol: '4', pn: '68' },
    { eng: 'bahurangi hi duniya', hin: 'बहुरंगी ही दुनिया', vol: '4', pn: '69' },
    { eng: 'sanga sanga sanga tuja ichar', hin: 'सांग सांग सांग तुजा इचार', vol: '4', pn: '70' },
    { eng: 'tujha bhakticha lala', hin: 'तुझा भक्तिचा लळा', vol: '4', pn: '71' },
    { eng: 'vare majanu tujhi prit re', hin: 'वारे मजनू तूझी प्रीत रे', vol: '4', pn: '72' },
    { eng: 'tu gokulcha re', hin: 'तू गोकुळचा रे', vol: '4', pn: '73' },
    { eng: 'girikanyechya pathi adathale', hin: 'गिरिकन्येच्या पथी अडथळे', vol: '4', pn: '74' },
    { eng: 'sadguru mi tujhe', hin: 'सदुगरू मी तुझे', vol: '4', pn: '75' },
    { eng: 'majha guljar rani', hin: 'माझा गुलजार राणी', vol: '4', pn: '76' },
    { eng: 'mich nivdla majhyasathi', hin: 'मीच निवडला माझ्यासाठी', vol: '4', pn: '77' },
    { eng: 'mardani tujhi mishi', hin: 'मर्दानी तुझी मिशी', vol: '4', pn: '78' },
    { eng: 'harlay mi mhor', hin: 'हारलाय मी म्होर', vol: '4', pn: '79' },
    { eng: 'bhaktirsachya sutlya dhara', hin: 'भक्तिरसाच्या सुटल्या धारा', vol: '4', pn: '80' },
    { eng: 'kunashi vadave dukh', hin: 'कुणाशी वदावे दुख', vol: '4', pn: '81' },
    { eng: 'nad ithe kashtani', hin: 'नाद इथे कष्टानी', vol: '4', pn: '82' },
    { eng: 'datanvarti chadhali lali', hin: 'दातांवरती चढली लाली', vol: '4', pn: '83' },
    { eng: 'mhatara bole shiv shiv', hin: 'म्हातारा बोले शिव शिव', vol: '4', pn: '84' },
    { eng: 'manasat tu rahun pranya', hin: 'माणसात तु राहून प्राण्या', vol: '4', pn: '86' },

    { eng: 'aj ghada to papacha bharla', hin: 'आज घडा तो पापाचा भरला', vol: '4', pn: '87' },
    { eng: 'sangu nako dusryala', hin: 'सांगू नको दुसर्याला', vol: '4', pn: '88' },
    { eng: 'te pandharpur', hin: 'ते पंढरपूर', vol: '4', pn: '89' },
    { eng: 'dev nase kevha duri', hin: 'देव नसे केव्हा दूरी', vol: '4', pn: '90' },
    { eng: 'pori g jau nako bolun', hin: 'पोरी ग जाऊ नको बोलून', vol: '4', pn: '91' },
    { eng: 'mardgiri dadachi ti geli', hin: 'मर्दगिरी दादाची ती गेली', vol: '4', pn: '92' },
    { eng: 'jahlis mata ata', hin: 'जाहलीस माता आता', vol: '4', pn: '93' },
    { eng: 'lal hariche anek', hin: 'लाल हरीचे अनेक', vol: '4', pn: '94' },
    { eng: 'ahe mala thave', hin: 'आहे मला ठावे', vol: '4', pn: '95' },
    { eng: 'patak jhale far', hin: 'पातक झाले फार', vol: '4', pn: '96' },
    { eng: 'pahu dya kon', hin: 'पाहु द्दा कोण', vol: '4', pn: '97' },
    { eng: 'aikun saval majha', hin: 'ऐकून सवाल माझा', vol: '4', pn: '98' },
    { eng: 'mi shisya mam gurucha', hin: 'मी शिष्य मम गुरूचा', vol: '4', pn: '99' },
    { eng: 'devmanse ahet majha', hin: 'देवमाणसे आहेत माझा', vol: '4', pn: '100' },
    { eng: 'mav tithe dev to', hin: 'माव तिथे देव तो', vol: '4', pn: '101' },
    { eng: 'ya vishvavarti', hin: 'या विश्वावरती', vol: '4', pn: '102' },
    { eng: 'bandhu hindu', hin: 'बंधू हिंदू', vol: '4', pn: '103' },
    { eng: 'jay adinath', hin: 'जय आदिनाथ', vol: '4', pn: '104' },
    { eng: 'panchavatichya vate', hin: 'पंचवटीच्या वाटे', vol: '4', pn: '106' },
    { eng: 'tav divy kupeke', hin: 'तव दिव्य कुपेचे', vol: '4', pn: '107' },
    { eng: 'tumhi nasatana sdagururaya', hin: 'तुम्ही नसताना सदागुरुराया', vol: '4', pn: '108' },
    { eng: 'gau to gau mai kya', hin: 'गाऊ तो गाऊ मै क्या', vol: '4', pn: '109' },
    { eng: 'dam dam damru jy', hin: 'डम डम डमरू जय', vol: '4', pn: '110' },
    { eng: 'digambara digambara', hin: 'दिगंबरा दिगंबरा', vol: '4', pn: '111' },
    { eng: 'kale na kuna re', hin: 'कळे ना कुणा रे', vol: '4', pn: '112' },
    { eng: 'antrichya kala kalati', hin: 'अंतरीच्या कळा कळती', vol: '4', pn: '113' },
    { eng: 'dekho nahi aj kabhi', hin: 'देखो नही आज कभी', vol: '4', pn: '114' },
    { eng: 'nako lavu ladi godi', hin: 'नको लावु लाडी गोडी', vol: '4', pn: '115' },

    { eng: 'golsadivali ali', hin: 'गोलसाडीवाली आली', vol: '4', pn: '116' },
    { eng: 'bap navaricha gurgur', hin: 'बाप नवरीचा गुरगुर', vol: '4', pn: '117' },
    { eng: 'sonalbay devane', hin: 'सोनालबाय देवाने', vol: '4', pn: '118' },
    { eng: 'haulula maje', hin: 'हौलुला माजे', vol: '4', pn: '119' },
    { eng: 'dharati vari jiv ha', hin: 'धरती वरी जीव हा', vol: '4', pn: '120' },
    { eng: 'vat chukalele nvre', hin: 'वाट चुकलेले नवरे', vol: '4', pn: '121' },
    { eng: 'hoin mi tar mises', hin: 'होईन मी तर मिसेस', vol: '4', pn: '122' },
    { eng: 'gaurinandana', hin: 'गौरीनंदना', vol: '4', pn: '123' },
    { eng: 'tujhya chintnat vel jai', hin: 'तुझ्या चिंतनात वेळ जाई', vol: '4', pn: '124' },
    { eng: 'sukhi kon ahe', hin: 'सुखी कोण आहे', vol: '4', pn: '125' },
    { eng: 'ya jagi deva', hin: 'या जगी देवा', vol: '4', pn: '126' },
    { eng: 'murti ganeshachi', hin: 'मर्ती गणेशाची', vol: '4', pn: '127' },
    { eng: 'dhir dhar palbhar mansa', hin: 'धीर धर पळभर माणसा', vol: '4', pn: '128' },
    { eng: 'tu bal guni', hin: 'तू बाळ गुणी', vol: '4', pn: '129' },
    { eng: 'rahili n shobha', hin: 'राहिली न शोभा', vol: '4', pn: '130' },
    { eng: 'vithu mandiri tujla', hin: 'विठू मंदिरी तुजला', vol: '4', pn: '131' },
    { eng: 'narichya pudhe kasa', hin: 'नारीच्या पुढे कसा', vol: '4', pn: '132' },
    { eng: 'dete madhur fulancha', hin: 'देते मधुर फुलांचा', vol: '4', pn: '133' },
    { eng: 'nam tujhe gha', hin: 'नाम तुझे घेता', vol: '4', pn: '134' },
    { eng: 'marave pari kirtichya', hin: 'मरावे परी किर्तीच्या', vol: '4', pn: '135' },
    { eng: 'gela kalakaratun', hin: 'गेला कलाकारातुन', vol: '4', pn: '136' },
    { eng: 'tula vatene jatana', hin: 'तुला वाटेने जाताना', vol: '4', pn: '137' },
    { eng: 'savdhan', hin: 'सावधान', vol: '4', pn: '138' },
    { eng: 'nav ya gavat', hin: 'नाव या गावात', vol: '4', pn: '139' },
    { eng: 'dongarala vedha deun', hin: 'डोंगराला वेढा देऊन', vol: '4', pn: '140' },

    { eng: 'rachilis pruthvi kaishi', hin: 'रचिलिस पृथ्वी कैशी', vol: '4', pn: '141' },
    { eng: 'manava manava vat', hin: 'मानवा मानवा वाट', vol: '4', pn: '142' },
    { eng: 'tisri payari', hin: 'तिसरी पायरी', vol: '4', pn: '143' },
    { eng: 'kapade reshmi', hin: 'कपडे रेशमी', vol: '4', pn: '144' },
    { eng: 'ghadibharaki vasti bare', hin: 'घडीभराची वस्ती बारे', vol: '4', pn: '145' },
    { eng: 'lagnala ali navari', hin: 'लग्नाला आली नवरी', vol: '4', pn: '146' },
    { eng: 'manjarila vinanti', hin: 'मांजरीला विनंती', vol: '4', pn: '147' },
    { eng: 'hi dhavala dhaval', hin: 'ही ढवळा ढवळ', vol: '4', pn: '148' },
    { eng: 'jhashicha daku', hin: 'झाशीचा डाकू', vol: '4', pn: '149' },
    { eng: 'ghya ghya pahun bolun', hin: 'घ्या घ्या पाहुन बोलुन', vol: '4', pn: '150' },
    { eng: 'vilamb nahi lage', hin: 'विलम्ब नाही लागे', vol: '4', pn: '151' },
    { eng: 'ya asha bayaka', hin: 'या अशा बायका', vol: '4', pn: '152' },
    { eng: 'kathin ale din ata', hin: 'कठिण आले दिन आता', vol: '4', pn: '153' },
    { eng: 'lok rokhun baghatyati', hin: 'लोक रोखून बघत्याती', vol: '4', pn: '154' },
    { eng: 'porich nashib lay thor', hin: 'पोरीच नाशिब लय थोर', vol: '4', pn: '155' },
    { eng: 'majhi rani sugaran', hin: 'माझी राणी सुगरण', vol: '4', pn: '156' },
    { eng: 'bachala janar nahis tu', hin: 'बचला जाणार नाहीस तू', vol: '4', pn: '157' },
    { eng: 'ranicha baga mumbila jethe', hin: 'राणीचा बागा मुम्बईला जेथे', vol: '4', pn: '158' },
    { eng: 'dev ghadvita dev', hin: 'देव घडविता देव', vol: '4', pn: '159' },
    { eng: 'rokhuni nako pahu', hin: 'रोखुनी नको पाहू', vol: '4', pn: '160' },
    { eng: 'boluni nako jau', hin: 'बोलूनी नको जाऊ', vol: '4', pn: '161' },
    { eng: 'tond pahun tujhe', hin: 'तोंड पाहून तुझे', vol: '4', pn: '162' },
    { eng: 'jar ka sarla padar', hin: 'जर का सरला पदर', vol: '4', pn: '163' },
    { eng: 'bharel kadhi ghtaka', hin: 'भरेल कधी घटका', vol: '4', pn: '164' },
    { eng: 'alank ki thodyavr', hin: 'आलंक की थोड्यावर', vol: '4', pn: '165' },

    { eng: 'malhari deva malhari', hin: 'मल्हारी देवा मल्हारी', vol: '4', pn: '166' },
    { eng: 'jay ambe devi jay', hin: 'जय अंबे देवी जय', vol: '4', pn: '167' },
    { eng: 'lakh molkachi ti', hin: 'लाख मोल्काची ती', vol: '4', pn: '168' },
    { eng: 'ek bhetit ga', hin: 'एक भेटीत ग', vol: '4', pn: '169' },
    { eng: 'deshasathi karu balidan', hin: 'देशासाठी करू बलिदान', vol: '4', pn: '170' },
    { eng: 'bharatiy mahila', hin: 'भारतीय महिला', vol: '4', pn: '171' },
    { eng: 'ti god kaishi', hin: 'ती गोड कैशी', vol: '4', pn: '172' },
    { eng: 'sakhe mithoni mhanuya gani', hin: 'सखे मिठोनी म्हूणया गाणी', vol: '4', pn: '173' },
    { eng: 'raja rani apan', hin: 'राजा राणी आपण', vol: '4', pn: '174' },
    { eng: 'mard gadi tu', hin: 'मर्द गडी तू', vol: '4', pn: '175' },
    { eng: 'tujh majh nat kasal', hin: 'तुझ माझ नात कसलं', vol: '4', pn: '176' },
    { eng: 'tujh majh nat patal', hin: 'तुझ माझ नात पटलं', vol: '4', pn: '177' },
    { eng: 'kulavantachi hi kanya', hin: 'कुलवंताची ही कन्या', vol: '4', pn: '178' },
    { eng: 'deh jyane ghadvila', hin: 'देह ज्याने घडविला', vol: '4', pn: '180' },
    { eng: 'chotas bandh ghar', hin: 'छोटस बांध घर', vol: '4', pn: '181' },
    { eng: 'khedyachya porijhi lagin', hin: 'खेड्याच्या पोरीझी लगीन', vol: '4', pn: '182' },
    { eng: 'mari khada an fodi ghada', hin: 'मारी खडा अन् फोडी घडा', vol: '4', pn: '183' },
    { eng: 'kadh kadi chal mar udi', hin: 'काढ कडी चल मार उडी', vol: '4', pn: '184' },
    { eng: 'jarjar jhalcha ha shiv', hin: 'जर्जर झाल्का हा शिव', vol: '4', pn: '185' },
    { eng: 'gharghar firuni sanga nako', hin: 'घरघर फिरूनी सांग नको', vol: '4', pn: '186' },
    { eng: 'sajne tujhe ka', hin: 'सजणे तुझे का', vol: '4', pn: '187' },
    { eng: 'sajna majala nahi re patal', hin: 'सजणा मजला नाही रे पटलं', vol: '4', pn: '188' },
    { eng: 'ram rahimko sbhi dekhalo', hin: 'राम रहिमको सभी देखलो', vol: '4', pn: '189' },
    { eng: 'majha sakha pandharila', hin: 'माझा सखा पंढरीला', vol: '4', pn: '191' },
    { eng: 'alo sharani buddh da', hin: 'आलो शरणी बुध्द देवा', vol: '4', pn: '192' },
    { eng: 'najar vakdi bai', hin: 'नजर वाकडी बाई', vol: '4', pn: '193' },
    { eng: 'khare sanga tu', hin: 'खरे सांग तू', vol: '4', pn: '194' },

    { eng: 'dokyala bandhun firto feta', hin: 'डोक्याला बांधुन फिरतो फेटा', vol: '4', pn: '195' },
    { eng: 'doivar paniyaki ghagar', hin: 'डोईवर पाणियाची घागर', vol: '4', pn: '196' },
    { eng: 'ultya bomba ya chorachya', hin: 'उलट्या बोम्बा या चोराच्या', vol: '4', pn: '197' },
    { eng: 'janmkundali khoti tharli', hin: 'जन्मकुंडली खोटी ठरली', vol: '4', pn: '198' },
    { eng: 'bandhin mi re tuj khambala', hin: 'बांधिन मी रे तुज खाम्बाला', vol: '4', pn: '199' },
    { eng: 'bandhin mi ghar shejari tujhya', hin: 'बांधिन मी घर शेजारी तुझ्या', vol: '4', pn: '200' },
    { eng: 'mokat sutla ha vatela', hin: 'मोकाट सुटला हा वाटेला', vol: '4', pn: '201' },
    { eng: 'sod chhand baisun ganyacha', hin: 'सोड छंद बैसुन गाण्याचा', vol: '4', pn: '202' },
    { eng: 'ja ja jare vata', hin: 'जा जा जारे वाटेला', vol: '4', pn: '203' },
    { eng: 'sundar ahe bulbul', hin: 'सुंदर आहे बुलबुल', vol: '4', pn: '204' },
    { eng: 'are ja tavala', hin: 'अरे जा टवाळा', vol: '4', pn: '205' },
    { eng: 'najar bholibhali', hin: 'नजर भोळीभाळी', vol: '4', pn: '206' },
    { eng: 'kartvyache palan karnya', hin: 'कर्तव्याचे पालन करण्या', vol: '4', pn: '207' },
    { eng: 'dukhali re karangali', hin: 'दुखली रे करंगळी', vol: '4', pn: '208' },
    { eng: 'yala na manaval', hin: 'याला ना मानवलं', vol: '4', pn: '209' },
    { eng: 'aichya bhavachi ti lek', hin: 'आईच्या भावाची ती लेक', vol: '4', pn: '210' },
    { eng: 'prabhunam moth jagi manite', hin: 'प्रभूनाम मोठ जगी मानिते', vol: '4', pn: '211' },
    { eng: 'tujhe rup', hin: 'तुझे रूप', vol: '4', pn: '212' },
    { eng: 'manava tujhe karm', hin: 'मानवा तुझे कर्म', vol: '4', pn: '213' },
    { eng: 'hi rani majhi ahe', hin: 'ही राणी माझी आहे', vol: '4', pn: '214' },
    { eng: 'ya navanyane dival kadhal', hin: 'या नवन्याने दिवाळ काढलं', vol: '4', pn: '215' },
    { eng: 'ragane ka nighoni jayach', hin: 'रागाने का निघोनी जायच', vol: '4', pn: '216' },
    { eng: 'pakhara ja pandharila', hin: 'पाखरा जा पंढरीला', vol: '4', pn: '217' },
    { eng: 'prabhu re janm tu dila', hin: 'प्रभू रे जन्म तू दिला', vol: '4', pn: '218' },
    { eng: 'shri ganptis prarthna', hin: 'श्री गणपतीस प्रार्थना', vol: '4', pn: '219' },

    { eng: 'bhajan karito suru', hin: 'भजन करीतो सुरू', vol: '4', pn: '220' },
    { eng: 'tarnarahi parameshwar', hin: 'तारणाराही परमेश्वर', vol: '4', pn: '221' },
    { eng: 'hi pasarito jholi', hin: 'ही पसरीतो झोळी', vol: '4', pn: '222' },
    { eng: 'shri gurudev dattatry', hin: 'श्री गुरूदेव दत्तात्रय', vol: '4', pn: '223' },
    { eng: 'vandan tula he ganraya', hin: 'वंदन तुला हे गणराया', vol: '4', pn: '224' },
    { eng: 'ghume damarunad dole nagaraj', hin: 'घुमे डमरूनाद डोले नागराज', vol: '4', pn: '225' },
    { eng: 'majhya saine majha bhar vahila', hin: 'माझ्या साईने माझा भार वाहिला', vol: '4', pn: '226' },
    { eng: 'krupavant shriramala', hin: 'कृपावंत श्रीरामाला', vol: '4', pn: '227' },
    { eng: 'shri karisn bhgavan', hin: 'श्री कृष्ण भगवान', vol: '4', pn: '228' },
    { eng: 'pandharichya vithu vithu', hin: 'पंढरीच्या विठू विठू', vol: '4', pn: '229' },
    { eng: 'ninda athva vanda koni', hin: 'निंदा अथवा, वंदा कोणी', vol: '4', pn: '230' },
    { eng: 'darshan de de durge', hin: 'दर्शन दे, दे दुर्गे', vol: '4', pn: '231' },
    { eng: 'yog sadhna', hin: 'योग साधना', vol: '4', pn: '232' },
    { eng: 'shri paduranga', hin: 'श्री पाडुरंग', vol: '4', pn: '233' },
    { eng: 'sadguru sadguru', hin: 'सद्गुरु सद्गुरु', vol: '4', pn: '234' },
    { eng: 'thevi sukhi sarva', hin: 'ठेवी सुखी सर्वा', vol: '4', pn: '235' },
    { eng: 'gurudhyan kar tu', hin: 'गुरूध्यान कर तू', vol: '4', pn: '236' },
    { eng: 'vina chiplya tya', hin: 'विणा चिपळ्या त्या', vol: '4', pn: '237' },
    { eng: 'sant sang labhu de mala', hin: 'संत संग लाभू दे मला', vol: '4', pn: '238' },
    { eng: 'pandharichya natha gun gata', hin: 'पंढरीच्या नाथा गुण गाता', vol: '4', pn: '239' },
    { eng: 'vishv he rachile kaise', hin: 'विश्व हे रचिले कैसे', vol: '4', pn: '240' },
    { eng: 'anandacha din ugavla', hin: 'आनंदाचा दिन उगवला', vol: '4', pn: '242' },
    { eng: 'bhimam namo buddham', hin: 'भीमंम् नमो बुध्दम', vol: '4', pn: '243' },
    { eng: 'naka koni karu galbla', hin: 'नका कोणी करू गलबला', vol: '4', pn: '244' },
    { eng: 'sanga sanga sanga jnta', hin: 'सांगा सांगा सांगा जनतेला', vol: '4', pn: '245' },

    { eng: 'bhimachi kirti dnyanachi murti', hin: 'भिमाची किर्ती, ज्ञानाची मूर्ती', vol: '4', pn: '246' },
    { eng: 'harapla harapla bharatatun khara', hin: 'हरपला हरपला भारतातुन खरा', vol: '4', pn: '247' },
    { eng: 'jagatat gharoghar gaje', hin: 'जगतात घरोघर गाजे', vol: '4', pn: '248' },
    { eng: 'dosh kunacha dosh kunacha', hin: 'दोष कुणाचा, दोष कुणाचा', vol: '4', pn: '249' },
    { eng: 'pahile pahile rup', hin: 'पाहिले पाहिले रूप', vol: '4', pn: '250' },
    { eng: 'jagi bhimaine thor kary', hin: 'जगी भीमाईने थोर कार्य', vol: '4', pn: '251' },
    { eng: 'gajate ya jagi thor kirti', hin: 'गाजते या जगी थोर किर्ती', vol: '4', pn: '252' },
    { eng: 'thakala prasanga jar anibanicha', hin: 'ठाकला प्रसंग जर आणिबाणीचा', vol: '4', pn: '253' },
    { eng: 'bhimachi hi sena', hin: 'भीमाची ही सेना', vol: '4', pn: '254' },
    { eng: 'ya ya chala ali paha', hin: 'या या चला आली पहा', vol: '4', pn: '255' },
    { eng: 'romromi sadaiv to vasla', hin: 'रोमरोमी सैदव तो वसला', vol: '4', pn: '256' },
    { eng: 'o prativarshi tu yetana svargatuni', hin: 'ओ प्रतिवर्षी तू येताना स्वर्गातुनी', vol: '4', pn: '257' },
    { eng: 'puspavrushti kari tuhi parameshwara', hin: 'पुष्पवृष्टी करी तूही परमेश्वरा', vol: '4', pn: '258' },
    { eng: 'to to to to bagha kuthun kavla ala', hin: 'तो तो, तो तो, बघा कुठून कावळा आला', vol: '4', pn: '259' },
    { eng: 'yana diste majla pudhun', hin: 'येताना दिसते मजला पुढून', vol: '4', pn: '260' },
    { eng: 'nasha jhali far ki ti batli fodi', hin: 'नशा झाली फार की ती बाटली फोडी', vol: '4', pn: '261' },
    { eng: 'pandharpurchya jagajethichi', hin: 'पंढरपुरच्या जगजेठीची', vol: '4', pn: '262' },
    { eng: 'maj bhiti tuj bhiti duniya', hin: 'मज भिती तुज भिती दुनियेला', vol: '4', pn: '263' },
    { eng: 'tujhya alo dvari shai kar murari', hin: 'तुझ्या आलो द्वारी सही कर मुरारी', vol: '4', pn: '264' },
    { eng: 'nachati khelati bhakt he dolti', hin: 'नाचती खेळती भक्त हे डोलती', vol: '4', pn: '265' },
    { eng: 'jayjaykar jayjaykar', hin: 'जयजयकार जयजयकार', vol: '4', pn: '266' },

    { eng: 'gandhi neharu shastrijike', hin: 'गांधी नेहरू शास्त्रीजीचे', vol: '4', pn: '267' },
    { eng: 'ghara gharatun ya trunano', hin: 'घरा घरातुन या तरूणानो', vol: '4', pn: '268' },
    { eng: 'mukhyamantri sandesh deuni jagaviti te janta', hin: 'मुख्यमंत्री संदेश देऊनी जागविती ते जनतेला', vol: '4', pn: '269' },
    { eng: 'gudhya ubharuya fule udhlu ya', hin: 'गुढ्या उभारूया, फुले उधळु या', vol: '4', pn: '270' },
    { eng: 'shankh chalvile asankhy jivavar', hin: 'शंख चालविले असंख्य जीवावर', vol: '4', pn: '271' },
    { eng: 'ghotala kela angashi ala', hin: 'घोटाळा केला अंगाशी आला', vol: '4', pn: '272' },
    { eng: 'utha utha hodev devtanno', hin: 'उठा उठा होदेव देवतांनो', vol: '4', pn: '273' },
    { eng: 'styasathi simevarati chalu ase to ladha', hin: 'सत्यासाठी सिमेवरती- चालू असे तो लढा', vol: '4', pn: '274' },
    { eng: 'janatela disla avaj uthla', hin: 'जनतेला दिसला- आवाज उठला', vol: '4', pn: '275' },
    { eng: 'hak aikta indirachi dhavun yenara asava', hin: 'हाक ऐकता इंदिराची धावून येणारा असावा', vol: '4', pn: '276' },
    { eng: 'bharati nari ti avtari', hin: 'भारती नारी ती अवतारी', vol: '4', pn: '277' },
    { eng: 'far dhavshil khali padshil', hin: 'फार धावशील खाली पडशिल', vol: '4', pn: '278' },
    { eng: 'jahla svatantr jari bangala ata', hin: 'जाहला स्वतंत्र जरी बांगला आता', vol: '4', pn: '279' },
    { eng: 'sainikat vha bharati', hin: 'सैनिकात व्हा भरती', vol: '4', pn: '283' },
    { eng: 'harhar mhadev', hin: 'हरहर महादेव', vol: '4', pn: '284' },
    { eng: 'manvas updesh', hin: 'मानवास उपदेश', vol: '4', pn: '285' },
    { eng: 'narjanm labhla tula', hin: 'नरजन्म लाभला तुला', vol: '4', pn: '287' },
    { eng: 'dharati te najar', hin: 'धरती ते नजर', vol: '4', pn: '288' },
    { eng: 'chhakula majha far ganacha', hin: 'छकुला माझा फार गुणाचा', vol: '4', pn: '289' },
    { eng: 'he prabhu majla tu dakhiv vat re', hin: 'हे प्रभु मजला तू दाखिव वाट रे', vol: '4', pn: '290' },
    { eng: 'nako radhe yeu jodila', hin: 'नको राधे येऊ जोडिला', vol: '4', pn: '291' },
    { eng: 'sodun te shahar ale khedyavr', hin: 'सोडून ते शहर, आले खेड्यावर', vol: '4', pn: '292' },
    { eng: 'vinati majhi hi nari nara', hin: 'विनती माझी ही नारी नरा', vol: '4', pn: '293' },
    { eng: 'chala haddpar', hin: 'चला हद्दपार', vol: '4', pn: '294' },
    { eng: 'bhakti mhante ye ikde', hin: 'भक्ति म्हणते ये इकडे', vol: '4', pn: '295' },

    { eng: 'pandharis majha sakha paduranga', hin: 'पंढरीस माझा सखा पाडुरंग', vol: '4', pn: '296' },
    { eng: 'mahilecha mahima', hin: 'महिलेचा महिमा', vol: '4', pn: '297' },
    { eng: 'mahima aikuni man mohile', hin: 'महिमा ऐकूनी मन मोहिले', vol: '4', pn: '298' },
    { eng: 'karnar lagan mi ata', hin: 'करणार लग्न मी आता', vol: '4', pn: '300' },
    { eng: 'jata ho kuth ya ho ikad', hin: 'जाता हो कुठं या हो इकड', vol: '4', pn: '301' },
    { eng: 'gardit gardi ya munbila', hin: 'गर्दीत गर्दी या मुंबईला', vol: '4', pn: '302' },
    { eng: 'sajna majh he man vital', hin: 'सजणा माझ हे मन विटलं', vol: '4', pn: '303' },
    { eng: 'jare vihanga tu mar bharari', hin: 'जारे विहंगा तू मार भरारी', vol: '4', pn: '304' },
    { eng: 'bayko jagadamba', hin: 'बायको जगदम्बा', vol: '4', pn: '305' },
    { eng: 'distay bari bagatan sari', hin: 'दिसतय बरी बगतान सारी', vol: '4', pn: '306' },
    { eng: 'kay karun nahi janiv jithe', hin: 'काय करून नाही जाणिव जिथे', vol: '4', pn: '307' },
    { eng: 'te akash tujhe chandr tare tujhe re tujhe', hin: 'ते आकाश तुझे चंद्र तारे तुझे रे तुझे', vol: '4', pn: '308' },
    { eng: 'vajiv dhol', hin: 'वाजिव ढोल', vol: '4', pn: '309' },
    { eng: 'chandr tujha mich sakhaye', hin: 'चंद्र तुझा मीच सखये', vol: '4', pn: '310' },
    { eng: 'vishv jyane sthapan kele', hin: 'विश्व जयाने स्थापन केले', vol: '4', pn: '311' },
    { eng: 'prabhuchya thikani nase bhed bhav', hin: 'प्रभुच्या ठिकाणी नसे भेद भाव', vol: '4', pn: '312' },
    { eng: 'sada sukh labho', hin: 'सदा सुख लाभो', vol: '4', pn: '313' },
    { eng: 'yego yego dari', hin: 'येगो येगो दारी', vol: '4', pn: '314' },
    { eng: 'darshan dere dere bhagvanta', hin: 'दशर्न देरे देरे भगवंता', vol: '4', pn: '315' },
    { eng: 'dam dhar goma', hin: 'दम धर गोमा', vol: '4', pn: '316' },
    { eng: 'dev dhavle pahata', hin: 'देव धावले पाहता', vol: '4', pn: '317' },
    { eng: 'ala kuthla ha pavhana', hin: 'आला कुठला हा पाव्हाणा', vol: '4', pn: '318' },
    { eng: 'nako baila mokat tu sutu', hin: 'नको बैला मोकाट तू सुटू', vol: '4', pn: '319' },
    { eng: 'gal fugavuni donhi', hin: 'गाल फुगवुनी दोन्ही', vol: '4', pn: '320' },
    { eng: 'don kavadichi char fule', hin: 'दोन कवडीची चार फुले', vol: '4', pn: '321' },

    { eng: 'roj hila mi deto', hin: 'रोज हिला मी देतो', vol: '4', pn: '322' },
    { eng: 'kadhuya vari', hin: 'काढूया वारी', vol: '4', pn: '323' },
    { eng: 'mansachya adhi tu', hin: 'माणसाच्या आधी तू', vol: '4', pn: '324' },
    { eng: 'yeshil ata vathani', hin: 'येशिल आता वठणी', vol: '4', pn: '326' },
    { eng: 'don dole distat bhole', hin: 'दोन डोळे दिसतात भोळे', vol: '4', pn: '327' },
    { eng: 'radat yeto radvun jato', hin: 'रडत येतो रडवून जातो', vol: '4', pn: '328' },
    { eng: 'padratach rahu de', hin: 'पदरातच राहू दे', vol: '4', pn: '329' },
    { eng: 'por chan naki dola', hin: 'पोर छान नाकी डोळा', vol: '4', pn: '330' },
    { eng: 'bhikshandehi shabd aikle', hin: 'भिक्षांदेही शब्द ऐकले', vol: '4', pn: '331' },
    { eng: 'gharvala gharvala', hin: 'घरवाला घरवाला', vol: '4', pn: '332' },
    { eng: 'najar tujhi bholi', hin: 'नजर तुझी भोळी', vol: '4', pn: '333' },
    { eng: 'jikde tikde bhatkat pranya', hin: 'जिकडे तिकडे भटकत प्राण्या', vol: '4', pn: '334' },
    { eng: 'sanga pori sanga pori manat kay', hin: 'सांग पोरी सांग पोरी मनात काय', vol: '4', pn: '335' },
    { eng: 'gori gori pan halvite man', hin: 'गोरी गोरी पान हलविते मान', vol: '4', pn: '336' },
    { eng: 'amrutacha jhara jashi olanduni', hin: 'अमृताचा झरा जाशी ओलांडुनी', vol: '4', pn: '337' },
    { eng: 'rastyachya katha kathala', hin: 'रस्त्याच्या काठा काठाला', vol: '4', pn: '338' },
    { eng: 'sadaryatach rahu de', hin: 'सदऱ्यातच राहू दे', vol: '4', pn: '339' },
    { eng: 'laj vate mala charchaughamadhe', hin: 'लाज वाटे मला चारचौघामधे', vol: '4', pn: '340' },
    { eng: 'kay kay mhan', hin: 'काय काय म्हण', vol: '4', pn: '341' },
    { eng: 'galat god hasashi', hin: 'गालात गोड हासशी', vol: '4', pn: '342' },
    { eng: 'mi charn tujhe dharita', hin: 'मी चरण तुझे धरिता', vol: '4', pn: '343' },
    { eng: 'mala sasubai', hin: 'मला सासुबाई', vol: '4', pn: '344' },
    { eng: 'kasa visaru mi tula', hin: 'कसा विसरू मी तला', vol: '4', pn: '345' },
    { eng: 'ayya ga ayya', hin: 'अय्या ग अय्या', vol: '4', pn: '346' },
    { eng: 'ya vaishakhala', hin: 'येता वैशाखाला', vol: '4', pn: '347' },

    { eng: 'aga aga bagh angat jhaga', hin: 'अग अग बघ अंगात झगा', vol: '4', pn: '348' },
    { eng: 'kavy lihinya sfurti labhu de', hin: 'काव्य लिहिण्या स्फूर्ती लाभू दे', vol: '4', pn: '349' },
    { eng: 'mhantat far najuk ahe', hin: 'म्हणतात फार नाजुक आहे', vol: '4', pn: '350' },
    { eng: 'baykocha bail', hin: 'बायकोचा बैल', vol: '4', pn: '351' },
    { eng: 'he hotel mumbiche shere panjab', hin: 'हे हॉटेल मुम्बईचे शेरे पंजाब', vol: '4', pn: '352' },
    { eng: 'vikates bajari stri dharm', hin: 'विकतेस बाजारी स्त्री धर्म', vol: '4', pn: '353' },
    { eng: 'jagi sarv sukhi asa koni nahi', hin: 'जगी सर्व सुखी असा कोणी नाही', vol: '4', pn: '355' },
    { eng: 'tujhi papi najar', hin: 'तुझी पापी नजर', vol: '4', pn: '356' },
    { eng: 'na janachi manachi kashi laj re', hin: 'ना जनाची मनाची कशी लाज रे', vol: '4', pn: '357' },
    { eng: 'ha mumbikadla balya', hin: 'हा मुम्बईकडला बाळ्या  ', vol: '4', pn: '358' },
    { eng: 'kanv munine pujanya didhle', hin: 'कण्व मुनीने पुजण्या दिधले', vol: '4', pn: '359' },
    { eng: 'porinki takrar rastorasti', hin: 'पोरींची तक्रार रस्तोरस्ती', vol: '4', pn: '360' },
    { eng: 'pativalya dhav ghe', hin: 'पाटीवाल्या धाव घे', vol: '4', pn: '361' },
    { eng: 'sukhe ladivala karu dya agai', hin: 'सुखे लडिवाला करू द्दा अगाई', vol: '4', pn: '362' },
    { eng: 'bhapaka bhari re', hin: 'भपका भारी रे', vol: '4', pn: '363' },
    { eng: 're nandalal nako maru khada re', hin: 'रे नंदलाल नको मारू खडा रे', vol: '4', pn: '364' },
    { eng: 'lakhlakat ha asun sara', hin: 'लखलकाट हा असून सारा', vol: '4', pn: '365' },
    { eng: 'mi ajvar kuthlyahi chhanda', hin: 'मी आजवर कुठल्याही छंदा', vol: '4', pn: '366' },
    { eng: 'na bhandan konache', hin: 'ना भांडण कोणाचे', vol: '4', pn: '367' },
    { eng: 'na kdhi ya kdhi', hin: 'ना कधी या कधी', vol: '4', pn: '368' },
    { eng: 'tu ghal ata ga pori', hin: 'तू घाल आता ग पोरी', vol: '4', pn: '369' },
    { eng: 'are dusman tu majha', hin: 'अरे दुष्मन तू माझा', vol: '4', pn: '370' },
    { eng: 'yamune tiri jhopla hindlal', hin: 'यमुने तीरी झोपला हिन्दलाल', vol: '4', pn: '371' }
];
