var p3 = [
    { eng: 'sangamachya mandirashi jo yati', hin: 'संगमाच्या मंदिराशी जो यति', vol: '3', pn: '2' },
    { eng: 'ughade asta donhi dole', hin: 'उघडे असता दोन्ही डोळे', vol: '3', pn: '3' },
    { eng: 'vishvat rahoniya vishv', hin: 'विश्वात राहोनिया विश्व', vol: '3', pn: '4' },
    { eng: 'sukhdukhacha svad detse', hin: 'सुखदुखाचा स्वाद देतसे', vol: '3', pn: '5' },
    { eng: 'kadhi kadhi n ulagade', hin: 'कधी कधी न उलगडे', vol: '3', pn: '7' },
    { eng: 'jivan safal jahle majhe', hin: 'जीवन सफल जाहले माझे', vol: '3', pn: '8' },
    { eng: 'he jiv kevha majhe jhale', hin: 'हे जीव केव्हा माझे झाले', vol: '3', pn: '10' },
    { eng: 'mi anti kay karito', hin: 'मी एकांती काय करीतो', vol: '3', pn: '11' },
    { eng: 'gurudarshan aj maj jhale', hin: 'गुरूदर्शन आज मज झाले', vol: '3', pn: '12' },
    { eng: 'tya saritechya bhitari rahuni', hin: 'त्या सरितेच्या भितरी राहूनी', vol: '3', pn: '13' },
    { eng: 'tuzi jethe marji', hin: 'तुझी जेथ मर्जी', vol: '3', pn: '14' },
    { eng: 'darshan ghde maj majhya sadguruche', hin: 'दर्शन घडे मज माझ्या सदुगरूचे', vol: '3', pn: '15' },
    { eng: 'ughde asata donhi dole', hin: 'उघडे असंता दोन्ही डोळे', vol: '3', pn: '16' },
    { eng: 'guru darshani majhe tan man', hin: 'गुरू दर्शनी माझे तन मन', vol: '3', pn: '17' },
    { eng: 'chandanacha gandh ala', hin: 'चंदनाचा गंध आला', vol: '3', pn: '18' },
    { eng: 'sangamachya tiri gandhrvpuri', hin: 'संगमाच्या तीरी- गंधर्वपुरी', vol: '3', pn: '19' },
    { eng: 'sadguru majhe ata jivani', hin: 'सद्गुरु माझे आता जीवनी', vol: '3', pn: '20' },
    { eng: 'majhya ghari samori', hin: 'माझ्या घरी सामोरी', vol: '3', pn: '21' },

    { eng: 'vatavarukshachya chhayekhali', hin: 'वटवृक्षाच्या छायेखाली', vol: '3', pn: '22' },
    { eng: 'shile bhitari shiv', hin: 'शिळे भितरी शिव', vol: '3', pn: '23' },
    { eng: 'tya gard jhad veli', hin: 'त्या गर्द झाड वेली', vol: '3', pn: '24' },
    { eng: 'chandanyat kurnache antharun', hin: 'चांदण्यात कुरणाचे अंथरूण', vol: '3', pn: '25' },
    { eng: 'audumbarachya chhayekhali', hin: 'औदुम्बराच्या छायेखाली', vol: '3', pn: '26' },
    { eng: 'jalashyatun premanande dhav', hin: 'जलाशयातून प्रेमानंदे धाव', vol: '3', pn: '27' },
    { eng: 'nishigandhachya tya sumanacha', hin: 'निशिगंधाच्या त्या सुमनाचा', vol: '3', pn: '28' },
    { eng: 'ujalalya tya sadanat', hin: 'उजळल्या त्या सदनात', vol: '3', pn: '30' },
    { eng: 'ya jivashivachya hoti', hin: 'या जीवाशिवाच्या होती', vol: '3', pn: '31' },
    { eng: 'dur vanat bhet jhali', hin: 'दूर वनात भेट झाली', vol: '3', pn: '32' },
    { eng: 'majhya devani athavan kadhali', hin: 'माझ्या देवानी आठवण काढली', vol: '3', pn: '34' },
    { eng: 'majhe man pratham harale', hin: 'माझे मान प्रथम हरले', vol: '3', pn: '35' },
    { eng: 'majhya tujhyat nahi antar', hin: 'माझ्या तुझ्यात नाही अंतर', vol: '3', pn: '36' },
    { eng: 'jyoti ujalat samai', hin: 'ज्योती उजळत समई', vol: '3', pn: '37' },
    { eng: 'deh amucha ha hariche', hin: 'देह आमुचा हा हरिचे', vol: '3', pn: '38' },
    { eng: 'pahin ajuni kiti', hin: 'पाहीन अजुनी किती', vol: '3', pn: '39' },
    { eng: 'bramh harihar jagi toch', hin: 'ब्रम्ह हरिहर जगी तोच', vol: '3', pn: '40' },
    { eng: 'mi veda jahlo jan ho', hin: 'मी वेडा जाहलो जन हो', vol: '3', pn: '41' },
    { eng: 'digambara jy digambara', hin: 'दिगंबरा जय दिगंबरा', vol: '3', pn: '42' },
    { eng: 'to usthiladhipti dhni', hin: 'तो उस्थिलाधीपती धनी', vol: '3', pn: '43' },
    { eng: 'ithe may odhi tithe', hin: 'इथे माय ओढी तिथे', vol: '3', pn: '44' },
    { eng: 'ya chakshuni mi to pahila', hin: 'या चक्षुनी मी, तो पाहिला', vol: '3', pn: '45' },
    { eng: 'ti rat datli murti', hin: 'ती रात दाटली मूर्ती', vol: '3', pn: '46' },
    { eng: 'ase psrla ya premacha', hin: 'असे पसरला या प्रेमाचा', vol: '3', pn: '47' },

    { eng: 'nayan band karata anand', hin: 'नयन बंद करता, आनंद', vol: '3', pn: '48' },
    { eng: 'paniyat narayan pahila', hin: 'पाणियात नारायण पाहिला', vol: '3', pn: '49' },
    { eng: 'madhur mandiratle nad kani', hin: 'मधुर मंदिरातले नाद कानी', vol: '3', pn: '50' },
    { eng: 'dattadani jivani hluhlu', hin: 'दत्तदेवानी जीवनी - हळूहळू', vol: '3', pn: '51' },
    { eng: 'je mam dola na dise', hin: 'जे मम् डोळा ना दिसे', vol: '3', pn: '52' },
    { eng: 'dolyas bhidta dole', hin: 'डोळ्यास भिडता डोळे', vol: '3', pn: '53' },
    { eng: 'asa mi tasa mi  thave', hin: 'असा मी तसा मी - ठावे', vol: '3', pn: '54' },
    { eng: 'te din adhiche smple', hin: 'ते दिन आधीचे सम्पले', vol: '3', pn: '55' },
    { eng: 'paravar tya pris pahila', hin: 'पारावर त्या परिस पाहिला', vol: '3', pn: '56' },
    { eng: 'jri jnsagaracha nirop ghetla', hin: 'जरी जनसागराचा निरोप घेतला', vol: '3', pn: '57' },
    { eng: 'majha devghar samori shriguru', hin: 'माझा देवघर सामोरी श्रुीगरू', vol: '3', pn: '58' },
    { eng: 'jivan pathavar firta', hin: 'जीवन पथावर फिरता', vol: '3', pn: '60' },
    { eng: 'jivani asta tufani sindhu', hin: 'जीवनी असता तुफानी सिंधु', vol: '3', pn: '61' },
    { eng: 'gatjanmachi majhi sapadli', hin: 'गतजन्माची माझी सापडली', vol: '3', pn: '62' },
    { eng: 'ya janmi darshanamrutane', hin: 'या जन्मी दर्शनामृताने', vol: '3', pn: '63' },
    { eng: 'godavarichya tati smadhit', hin: 'गोदावरीच्या तटी समाधीत', vol: '3', pn: '64' },
    { eng: 'gurumauli rudhirat majhya', hin: 'गुरूमाऊली रूधिरात माझ्या', vol: '3', pn: '66' },
    { eng: 'bhikshan dei shbd mdhur', hin: 'भिक्षां देई शब्द मधूर', vol: '3', pn: '68' },
    { eng: 'janshi na kaisha', hin: 'जाणशी ना कैशा', vol: '3', pn: '69' },
    { eng: 'vata soda mi jato pudhe', hin: 'वाटा सोडा मी जातो पुढे', vol: '3', pn: '70' },
    { eng: 'jhad ek bakuliche  dat', hin: 'झाड एक बकुळिचे - दाट', vol: '3', pn: '71' },
    { eng: 'othkh nsta tujhi ni majhi', hin: 'ओठख नसता तुझी नि माझी', vol: '3', pn: '72' },
    { eng: 'agala annd labh ganagapuri', hin: 'आगळा आनंद लाभ गाणगापूरी', vol: '3', pn: '73' },
    { eng: 'jivani kse nvchaitany', hin: 'जीवनी कसे नवचैतन्य', vol: '3', pn: '74' },
    { eng: 'karta ase narayan lila', hin: 'कर्ता असे नारायण - लीला', vol: '3', pn: '75' },
    { eng: 'mi kon ha kuthla', hin: 'मी कोण हा कुठला', vol: '3', pn: '76' },

    { eng: 'svpnat je n pahile', hin: 'स्वप्नात जे न पाहिले', vol: '3', pn: '77' },
    { eng: 'mi kasa mala thave nahi', hin: 'मी कसा मला ठावे नाही', vol: '3', pn: '78' },
    { eng: 'char acharat mi kadhi bahu', hin: 'चर अचरात मी कधी बहू', vol: '3', pn: '79' },
    { eng: 'tujhyamulech mi ase majhyat', hin: 'तुझ्यामुळेच मी असे, माझ्यात', vol: '3', pn: '80' },
    { eng: 'hi jari majhi kudi', hin: 'ही जरी माझी कुडी,', vol: '3', pn: '81' },
    { eng: 'hari baheri hari antari', hin: 'हरी बाहेरी - हरी अंतरी', vol: '3', pn: '82' },
    { eng: 'mi smaran tujhe kariti', hin: 'मी स्मरण तुझे करीती', vol: '3', pn: '83' },
    { eng: 'tujhich karito aradhna', hin: 'तुझीच करीतो, आराधना', vol: '3', pn: '84' },
    { eng: 'sugandh adhi nantar prachiti', hin: 'सुगंध आधी नंतर प्रचिती', vol: '3', pn: '85' },
    { eng: 'ase natki shriguru munivar', hin: 'असे नाटकी श्रुीगरू मुनिवर', vol: '3', pn: '86' },
    { eng: 'avati bhavatichi janta jhopli', hin: 'अवती भवतीची जनता झोपली', vol: '3', pn: '87' },
    { eng: 'achuk najare najar bhidali', hin: 'अचुक नजरे नजर भिडली', vol: '3', pn: '88' },
    { eng: 'mam jivanache jatak kathile', hin: 'ममजीवनाचे जातक कथिले,', vol: '3', pn: '89' },
    { eng: 'tech rup an tich lakshne', hin: 'तेच रूप अन् तीच लक्षणे', vol: '3', pn: '90' },
    { eng: 'mi khelto khelvito', hin: 'मी खेळतो, खेळवितो', vol: '3', pn: '91' },
    { eng: 'davitandhari gaojiri traimurti', hin: 'दाविते अंधारी गोजिरी त्रैमूर्ती', vol: '3', pn: '92' },
    { eng: 'dokavta mi srovarat', hin: 'डोकावता मी सरोवरात', vol: '3', pn: '93' },
    { eng: 'umtle valuvar paul', hin: 'उमटले वाळूवर पाऊल', vol: '3', pn: '94' },
    { eng: 'dukhi pidit jnatun', hin: 'दुखी पिडीत जनातून', vol: '3', pn: '95' },
    { eng: 'bhetali gurushikhar mi', hin: 'भेटली, गुरूशिखर मी', vol: '3', pn: '96' },
    { eng: 'bolat asuni doghe apan', hin: 'बोलत असूनी, दोघे आपण', vol: '3', pn: '97' },
    { eng: 'jari majhi kaya harichich maya', hin: 'जरी माझी काया । हरिचिच माया', vol: '3', pn: '99' },
    { eng: 'bmhrndha jhakuni gheuni', hin: 'बम्हरंधा, झाकुनी घेऊनी', vol: '3', pn: '100' },

    { eng: 'jivas ved lagale', hin: 'जीवास वेड लागले', vol: '3', pn: '101' },
    { eng: 'mi nivant hoto bslo', hin: 'मी निवांत होतो बसलो', vol: '3', pn: '102' },
    { eng: 'ramkrushn hari', hin: 'रामकृष्ण हरी', vol: '3', pn: '103' },
    { eng: 'dattarajane jivani haluhalu', hin: 'दत्तराजाने जीवनी - हळूहळू', vol: '3', pn: '104' },
    { eng: 'tujvina kon purvil', hin: 'तुजवीणा कोण पुरविल', vol: '3', pn: '110' },
    { eng: 'ashvatthavarukshasamip dhyan', hin: 'आश्वत्थवृक्षासमिप ध्यान', vol: '3', pn: '112' },
    { eng: 'nij bhaktache atipremache', hin: 'निज भक्ताचे अतिप्रेमाचे', vol: '3', pn: '113' },
    { eng: 'sagun nirgun ekachi praman', hin: 'सुगण निर्गुण एकची प्रमाण', vol: '3', pn: '114' },
    { eng: 'jo datta konas na gathla', hin: 'जो दत्त कोणास ना गाठला', vol: '3', pn: '115' },
    { eng: 'charan kamal tujhe daivt majhe', hin: 'चरण कमळ तुझे दैवत माझे', vol: '3', pn: '116' },
    { eng: 'tya gatjanmachya smruti', hin: 'त्या गतजन्माच्या स्मृती', vol: '3', pn: '117' },
    { eng: 'ti pahili bhet majhi', hin: 'ती पहिली भेट माझी', vol: '3', pn: '118' },
    { eng: 'vichar kona sanga majha', hin: 'विचार कोणा सांग माझा', vol: '3', pn: '119' },
    { eng: 'godavarichya tati baisalo', hin: 'गोदावरीच्या तटी बैसलो', vol: '3', pn: '120' },
    { eng: 'janmojanmi daivt majhe antari', hin: 'जन्मोजन्मी दैवत माझे - अंतरी', vol: '3', pn: '121' },
    { eng: 'niranjnat ti shantamay', hin: 'निरांजनात ती शांतमय', vol: '3', pn: '122' },
    { eng: 'mauliche rup na nave', hin: 'माऊलीचे रूप ना नवे', vol: '3', pn: '123' },
    { eng: 'hote manat tech mla labhle', hin: 'होते मनात तेच मला लाभले', vol: '3', pn: '124' },
    { eng: 'tujhe majhe nate deva kuna', hin: 'तुझे माझे नाते देवा कुणा', vol: '3', pn: '125' },
    { eng: 'nishigandhacha sugandh athave', hin: 'निशिगंधाचा सुगंध आठवे', vol: '3', pn: '126' },
    { eng: 'majhi dattai dattai', hin: 'माझी दत्ताई दत्ताई', vol: '3', pn: '127' },
    { eng: 'bola om datta bola', hin: 'बोला ॐ दत्त बोला', vol: '3', pn: '128' },
    { eng: 'bhaktimarga god avit', hin: 'भक्तिमार्ग गोड - अविट', vol: '3', pn: '129' },
    { eng: 'jithe jato tethe majha', hin: 'जिथे जातो तेथे माझा', vol: '3', pn: '130' },
    { eng: 'tujhya malakikache ghar', hin: 'तुझ्या मालकीचे आहे घर', vol: '3', pn: '131' },

    { eng: 'yoni yoni priya jivacha', hin: 'योनी योनी प्रिय जीवाचा', vol: '3', pn: '132' },
    { eng: 'prabhu datta maza', hin: 'प्रभू दत्त माझा', vol: '3', pn: '133' },
    { eng: 'kalyan bhv', hin: 'कल्याण भव', vol: '3', pn: '134' },
    { eng: 'jethe jau tethe hari', hin: 'जेथे जाऊ तेथे हरि', vol: '3', pn: '136' },
    { eng: 'mi vishvat antari vishv', hin: 'मी विश्वात, अंतरी विश्व', vol: '3', pn: '137' },
    { eng: 'madhyaratr ek prbhu darshanachi', hin: 'मध्यरात्र एक प्रभु दर्शनाची', vol: '3', pn: '138' },
    { eng: 'digambara jy digambara', hin: 'दिगम्बरा जय दिगम्बरा', vol: '3', pn: '140' },
    { eng: 'vajati kuthle runjhun painjan', hin: 'वाजती कुठले, रुणझुण पैंजण', vol: '3', pn: '141' },
    { eng: 'jivanat mi ya firata', hin: 'जीवनात मी या फिरता', vol: '3', pn: '142' },
    { eng: 'divytavachi ali prchiti', hin: 'दिव्यत्वाची आली प्रचीती', vol: '3', pn: '143' },
    { eng: 'majhe sambhaliti dhan', hin: 'माझे साम्भाळीती धन', vol: '3', pn: '144' },
    { eng: 'dnyankala majhi apuri', hin: 'ज्ञानकळा माझी अपूरी', vol: '3', pn: '145' },
    { eng: 'taranara jaganya sange', hin: 'तारणारा जगण्या सांगे', vol: '3', pn: '146' },
    { eng: 'vatavarukshachya fandivarti', hin: 'वटवृक्षाच्या फांदीवरती', vol: '3', pn: '147' },
    { eng: 'saudaminitil bhase prasann', hin: 'सौदामिनीतील भासे प्रसंन्न', vol: '3', pn: '148' },
    { eng: 'sadguruncha darshanachi', hin: 'सद्गुरूंचा दर्शनाची', vol: '3', pn: '149' },
    { eng: 'shastrahuni hi mahabhayankar', hin: 'शस्त्राहुनी ही महाभयंकर', vol: '3', pn: '152' },
    { eng: 'nyayadhishala nyay na', hin: 'न्यायाधिशाला न्याय ना', vol: '3', pn: '154' },
    { eng: 'narayana tav charana mi', hin: 'नारायणा तव चरणा मी', vol: '3', pn: '155' },
    { eng: 'majhya manat je navhate', hin: 'माझ्या मनात जे नव्हते', vol: '3', pn: '156' },
    { eng: 'ata vruksh krtavyacha', hin: 'आता वृक्ष कर्ताव्याचा', vol: '3', pn: '157' },
    { eng: 'chukale aselhi amuche', hin: 'चुकले असेलही आमुचे', vol: '3', pn: '158' },

    { eng: 'kadhi manavar tyachya karashil', hin: 'कधी मनावर त्याच्या करशिल', vol: '3', pn: '160' },
    { eng: 'savdhan savdhan', hin: 'सावधान सावधान', vol: '3', pn: '162' },
    { eng: 'antarat rahuni to', hin: 'अंतरात राहूनी - तो', vol: '3', pn: '163' },
    { eng: 'tujha romromi shriguru', hin: 'तुझा रोमरोमी श्रीगुरू', vol: '3', pn: '164' },
    { eng: 'jari karishi tu nijsukhastav', hin: 'जरी करीशी तू निजसुखास्तव', vol: '3', pn: '166' },
    { eng: 'as n dharata pad padari', hin: 'आस न धरता पद पदरी', vol: '3', pn: '167' },
    { eng: 'he brahmandkartya re', hin: 'हे ब्रम्हांडकर्त्या रे', vol: '3', pn: '168' },
    { eng: 'kalyanbhav vardan', hin: 'कल्याणभव वरदान', vol: '3', pn: '169' },
    { eng: 'jhijale chandan lavun tanman', hin: 'झिजले चंदन लावून तनमन', vol: '3', pn: '170' },
    { eng: 'nirdoshala dosh deshi tu', hin: 'निर्दोषाला दोष देशी तू', vol: '3', pn: '171' },
    { eng: 'ka sanga manodevte', hin: 'का सांग मनोदेवते', vol: '3', pn: '174' },
    { eng: 'vichar karun tu mana dhav re', hin: 'विचार करून तू मना धाव रे', vol: '3', pn: '175' },
    { eng: 'nam kadhi na dukhvi mana', hin: 'नाम कधी ना दूखवी मना', vol: '3', pn: '176' },
    { eng: 'manache vichar manat rahati', hin: 'मनाचे विचार मनात रहाती', vol: '3', pn: '177' },
    { eng: 'jare mana ja ja bhitri', hin: 'जारे मना जा जा भितरी', vol: '3', pn: '178' },
    { eng: 'paristhitishi khiluni rahshil', hin: 'परिस्थितीशी खिळूनी राहशील', vol: '3', pn: '179' },
    { eng: 'man sange vinvoni dya', hin: 'मन सांगे विनवोनी दया', vol: '3', pn: '180' },
    { eng: 'bol mana bol preme abol', hin: 'बोल मना बोल प्रेमे अबोल', vol: '3', pn: '181' },
    { eng: 'nahi tyasi kale karm', hin: 'नाही त्यासी कळे कर्म', vol: '3', pn: '182' },
    { eng: 'ba re man thakali kudi', hin: 'बा रे मन थकली कुडी', vol: '3', pn: '184' },
    { eng: 'atmyachi hovo deva', hin: 'आत्म्याची होवो देवा,', vol: '3', pn: '185' },
    { eng: 'manane svaye hrudayat mandir kele', hin: 'मनाने स्वये हृदयात मंदिर केले', vol: '3', pn: '186' },
    { eng: 'manala gurudarshani agala', hin: 'मनाला गुरूदर्शनीं - आगळा', vol: '3', pn: '187' },

    { eng: 'jiv das vinvi mana', hin: 'जीव देवास विनवी मना', vol: '3', pn: '188' },
    { eng: 'tan man jethe aviratachi ramati', hin: 'तन मन जेथे अविरतची रमती', vol: '3', pn: '189' },
    { eng: 'vinvitse jiv manodevta', hin: 'विनवितसे, जीव मनोदेवतेला', vol: '3', pn: '190' },
    { eng: 'alya janmi uddharaya mana', hin: 'आल्या जन्मी उध्दाराया मना', vol: '3', pn: '191' },
    { eng: 'are manachya ghodyavarti', hin: 'अरे मनाच्या घोड्यावरती', vol: '3', pn: '192' },
    { eng: 'man dharm karm visro', hin: 'मन धर्म कर्म विसरो', vol: '3', pn: '193' },
    { eng: 'tan man jethe aviratachi ramati', hin: 'तन मन जेथे, अविरतची रमती', vol: '3', pn: '194' },
    { eng: 'prapnch kruni purnanande paramarthi', hin: 'प्रपंच करूनी पूर्णानंदे परमार्थी', vol: '3', pn: '195' },
    { eng: 'satynitichi vat kharokhar ya jivani', hin: 'सत्यनीतीची वाट खरोखर या जीवनी', vol: '3', pn: '198' },
    { eng: 'guru maulila sadaiv smarave', hin: 'गुरू माऊलीला सदैव स्मरावे', vol: '3', pn: '200' },
    { eng: 'he manuja tu nit', hin: 'हे मनुजा तू नित', vol: '3', pn: '201' },
    { eng: 'he manuja dhir dhari', hin: 'हे मनुजा धीर धरी', vol: '3', pn: '202' },
    { eng: 'are manva giravit jare', hin: 'अरे मानवा गिरवित जारे', vol: '3', pn: '203' },
    { eng: 'tu anandi raha honare', hin: 'तू आनंदी रहा होणारे', vol: '3', pn: '204' },
    { eng: 'bhetati dnyani tiri gange', hin: 'भेटती ज्ञानी तीरी गंगे', vol: '3', pn: '207' },
    { eng: 'kuni na kunacha', hin: 'कुणी ना कुणाचा', vol: '3', pn: '208' },
    { eng: 'kara sadhuseva puri', hin: 'करा साधूसेवा पुरी', vol: '3', pn: '210' },
    { eng: 'gururaya samarth ase tujhe', hin: 'गुरुराया समर्थ असे तुझे', vol: '3', pn: '211' },
    { eng: 'jivanat nana prsangi jiv haka', hin: 'जीवनात नाना प्रसंगी जीव हाका', vol: '3', pn: '212' },
    { eng: 'man ramvave sada dattadhami', hin: 'मन रमवावे सदा दत्तधामी', vol: '3', pn: '213' },
    { eng: 'nako ghabaru jivanat re', hin: 'नको घाबरु जीवनात रे', vol: '3', pn: '214' },
    { eng: 'antari kahi lapavu nako re', hin: 'अंतरी काही लपवू नको रे', vol: '3', pn: '216' },
    { eng: 'kay udya te na bare thave', hin: 'काय उद्या ते ना बरे ठावे', vol: '3', pn: '217' },

    { eng: 'dharativari nako jhalese ghar', hin: 'धरतीवरी नको झालेसे घर', vol: '3', pn: '218' },
    { eng: 'vel thambnar nahi', hin: 'वेळ थाम्बणार नाही', vol: '3', pn: '220' },
    { eng: 'rat jata punha ahe', hin: 'रात जाता पुन्हा आहे', vol: '3', pn: '221' },
    { eng: 'jo dev vishvat nahi', hin: 'जो देव विश्वात नाही', vol: '3', pn: '222' },
    { eng: 'kadhi kay hoi adhi', hin: 'कधी काय होई आधी', vol: '3', pn: '224' },
    { eng: 'chaitany narayanas gathoni', hin: 'चैतन्य नारायणास गाठोनी', vol: '3', pn: '225' },
    { eng: 'ahe tula vardan', hin: 'आहे तुला वरदान', vol: '3', pn: '226' },
    { eng: 'he jiva he jiva jivashi khelu nako', hin: 'हे जीवा हे जीवा जिवाशी खेळू नको', vol: '3', pn: '228' },
    { eng: 'ishvarachya praptisathi ase', hin: 'ईश्वराच्या प्राप्तीसाठी असे', vol: '3', pn: '229' },
    { eng: 'jhale gele sare visroni', hin: 'झाले गेले सारे विसरोनी', vol: '3', pn: '230' },
    { eng: 'manavari sayyam manasa', hin: 'मनावरी संयम माणसा', vol: '3', pn: '231' },
    { eng: 'tya mayela bhalu nako', hin: 'त्या मायेला भाळू नको', vol: '3', pn: '232' },
    { eng: 'namo narayan narayan nam ghe', hin: 'नमो नारायण नारायण नाम घे', vol: '3', pn: '233' },
    { eng: 'bhav tochi dev dev duja nahi', hin: 'भाव तोचि देव देव दुजा नाही', vol: '3', pn: '234' },
    { eng: 'ghe tu gheshil tituke ghe', hin: 'घे तू घेशिल तितुके घे', vol: '3', pn: '235' },
    { eng: 'avirat ghe nit nam', hin: 'अविरत घे नित नाम', vol: '3', pn: '236' },
    { eng: 'bandhuno bandhuno bandhuno', hin: 'बंधूनो बंधूनो बंधूनो', vol: '3', pn: '237' },
    { eng: 'padlelyala uchalun gheto dut kharachi', hin: 'पडलेल्याला उचलून घेतो दूत खराची', vol: '3', pn: '238' },
    { eng: 'sadguru nij bhaktache hit kari', hin: 'सदुगरू निज भक्ताचे हित करी', vol: '3', pn: '239' },
    { eng: 'vaisnavajan je te purushottam tya', hin: 'वैष्णवजन जे ते पुरूषोत्तम त्या', vol: '3', pn: '240' },
    { eng: 'chaitany svarup ase bhagvant', hin: 'चैतन्य स्वरूप असे भगवंत', vol: '3', pn: '241' },
    { eng: 'bola bare bola ram krushn hari', hin: 'बोला बारे बोला राम कृष्ण हरि', vol: '3', pn: '242' },
    { eng: 'ase hi kudi re ghadi do', hin: 'असे ही कुडी रे घडी दो', vol: '3', pn: '244' },
    { eng: 'jyache jaise kulachar', hin: 'ज्याचे जैसे कुळाचार', vol: '3', pn: '245' },
    { eng: 'nako ghabaru jivanat re', hin: 'नको घाबरु जीवनात रे', vol: '3', pn: '246' },

    { eng: 'manuja re ghyavi smaradhna', hin: 'मनुजा रे घ्यावी समाराधना', vol: '3', pn: '247' },
    { eng: 'he ful ata nahi adhik', hin: 'हे फुल आता नाही अधिक', vol: '3', pn: '248' },
    { eng: 'padtyala gurucha sada adhar', hin: 'पडत्याला गुरूचा सदा आधार', vol: '3', pn: '249' },
    { eng: 'thevile anante taisechi rahave', hin: 'ठेविले अनंते तैसेची रहावे', vol: '3', pn: '250' },
    { eng: 'gharagharat hi samasya tya', hin: 'घराघरात ही समस्या त्या', vol: '3', pn: '251' },
    { eng: 'karm karanya adhi kr vichar', hin: 'कर्म करण्या आधी कर विचार', vol: '3', pn: '254' },
    { eng: 'deh nashivnt ishvar virajman', hin: 'देह नाशिवंत ईश्वर विराजमान', vol: '3', pn: '256' },
    { eng: 'karm kari ayusyat vichar', hin: 'कर्म करी आयुष्यात विचार', vol: '3', pn: '257' },
    { eng: 'ida pida tya ajun gharat', hin: 'इडा पिडा त्या अजुन घरात', vol: '3', pn: '258' },
    { eng: 'majha gurudev andhalyachi kathi', hin: 'माझा गुरूदेव आँधळ्याची काठी', vol: '3', pn: '260' },
    { eng: 'kudi sachetan chaitany raja kri', hin: 'कुडी सचेतन चैतन्य राजा करी', vol: '3', pn: '261' },
    { eng: 'ramanam ya mukhat ghe re', hin: 'रामनाम या मुखात घे रे', vol: '3', pn: '262' },
    { eng: 'ekant kar vichar', hin: 'एकांत कर विचार', vol: '3', pn: '263' },
    { eng: 'tanacha dhanacha bajar bharla', hin: 'तनाचा धनाचा बाजार भरला', vol: '3', pn: '264' },
    { eng: 'mayabandhnat hoy kadhi ghat', hin: 'मायाबंधनात होय कधी घात', vol: '3', pn: '265' },
    { eng: 'vesh hi sadha adhyatmacha lavlesh', hin: 'वेष ही साधा अध्यात्माचा लवलेश', vol: '3', pn: '266' },
    { eng: 'manav janma yeun pranya', hin: 'मानव जन्मा येऊन प्राण्या', vol: '3', pn: '267' },
    { eng: 'kshan molacha ase jivanat', hin: 'क्षण मोलाचा असे जीवनात', vol: '3', pn: '268' },
    { eng: 'mansa re mansavar vishvas theu', hin: 'माणसा रे माणसावर विश्वास ठेऊ', vol: '3', pn: '269' },
    { eng: 'prapanchika paramarth kar', hin: 'प्रापंचिका परमार्थ कर', vol: '3', pn: '270' },
    { eng: 'sant mahatma sangaun gele', hin: 'संत महात्मा सांगून गेले', vol: '3', pn: '271' },
    { eng: 'lavchik dhaga ayusyacha', hin: 'लवचिक धागा आयुष्याचा', vol: '3', pn: '274' },
    { eng: 'dan didhle yathashakti', hin: 'दान दिधले यथाशक्ती', vol: '3', pn: '275' },
    { eng: 'mansa yeun janma jagare', hin: 'माणसा येऊन जन्मा जागरे', vol: '3', pn: '276' },
    { eng: 'lobh moh maya vichar', hin: 'लोभ मोह मायेचा विचार', vol: '3', pn: '278' },

    { eng: 'jhale te gange arpn ata savdhan', hin: 'झाले ते गंगे अर्पण आता सावधान', vol: '3', pn: '280' },
    { eng: 'badaltya paristhitit path chalatana', hin: 'बदलत्या परिस्थितीत पथ चालताना', vol: '3', pn: '281' },
    { eng: 'sanga nako kuna tya divy daivi', hin: 'सांग नको कुणा त्या दिव्य दैवी', vol: '3', pn: '282' },
    { eng: 'om datta om datta namachi godi', hin: 'ॐ दत्त ॐ दत्त नामाची गोडी', vol: '3', pn: '283' },
    { eng: 'padopadi svarthi nisvarthi far', hin: 'पदोपदी स्वार्थी निस्वार्थी फार', vol: '3', pn: '286' },
    { eng: 'kal vel nahi nam ghya', hin: 'काळ वेळ नाही नाम घ्या', vol: '3', pn: '287' },
    { eng: 'shani kali asati jari', hin: 'शनि कली असती जरी', vol: '3', pn: '288' },
    { eng: 'rinanubandh gat janmache', hin: 'ऋणानुबंध गत जन्माचे', vol: '3', pn: '289' },
    { eng: 'ghe dnyanache tu dhade ayushy ahe', hin: 'घे ज्ञानाचे तू धडे आयुष्य आहे', vol: '3', pn: '290' },
    { eng: 'tumhi kuthle amhi kuthle', hin: 'तुम्ही कुठले आम्ही कुठले', vol: '3', pn: '292' },
    { eng: 'shrigurunchi drushti rahe', hin: 'श्रुीगरूंची दृष्टी राहे', vol: '3', pn: '295' },
    { eng: 'ranangani tya ladhe n arjun', hin: 'रणांगणी त्या लढे न अर्जुन', vol: '3', pn: '296' },
    { eng: 'path he manva jivani ek', hin: 'पथ हे मानवा जीवनी एक', vol: '3', pn: '297' },
    { eng: 'tujhe nashib tujha hati', hin: 'तुझे नशिब तुझा हाती', vol: '3', pn: '298' },
    { eng: 'jaise jyache karm taise', hin: 'जैसे ज्याचे कर्म तैसे', vol: '3', pn: '299' },
    { eng: 'jauni durdur darshan gheshi', hin: 'जाऊनी दूरदूर दर्शन घेशी', vol: '3', pn: '300' },
    { eng: 'nako vyrth bhtku te', hin: 'नको व्यर्थ भटकू ते', vol: '3', pn: '301' },
    { eng: 'nvchaitany jiva bodh asa', hin: 'नवचैतन्य जीवा बोध असा', vol: '3', pn: '305' },
    { eng: 'he mansa tujhe nashib ahe', hin: 'हे माणसा तुझे नशिब आहे', vol: '3', pn: '306' },
    { eng: 'bhakthi fire to dilya', hin: 'भक्तही फिरे तो दिल्या', vol: '3', pn: '307' },
    { eng: 'radu nako bare pranya', hin: 'रडू नको बारे प्राण्या', vol: '3', pn: '308' },
    { eng: 'mansa laksh de sansari', hin: 'माणसा लक्ष दे संसारी', vol: '3', pn: '309' },
    { eng: 'sasr maher shari ganagapur', hin: 'सासर माहेर श्री गाणगापूर', vol: '3', pn: '310' },
    { eng: 'jivanat kadhi bharati ohoti', hin: 'जीवनात कधी भरती ओहोटी', vol: '3', pn: '311' },
    { eng: 'yogi trast jhala tar dharanikamp', hin: 'योगी त्रस्त झाला तर धरणीकंप', vol: '3', pn: '312' },

    { eng: 'kadhi kadhi tya jivani tujla', hin: 'कधी कधी त्य जीवनी तुजला', vol: '3', pn: '314' },
    { eng: 'te sukh an dukh bhogaya', hin: 'ते सुख अन् दुख भोगाया', vol: '3', pn: '315' },
    { eng: 'dharativari nako jhalese ghar', hin: 'धरतीवरी नको झालेसे घर', vol: '3', pn: '316' },
    { eng: 'kay pudhe kahik nahi', hin: 'काय पुढे काहीच नाही', vol: '3', pn: '318' },
    { eng: 'gupit tujhe mi fodu', hin: 'गुपित तुझे मी फोडू', vol: '3', pn: '320' },
    { eng: 'vaishnavjan firti jgati', hin: 'वैष्णवजन फिरती जगती', vol: '3', pn: '321' },
    { eng: 'ghadane ghadate na tula', hin: 'घडणे घडते ना तुला', vol: '3', pn: '322' },
    { eng: 'ahe bhakticha ha mla', hin: 'आहे भक्तिचा हा मळा', vol: '3', pn: '323' },
    { eng: 'dnyanacha to mala bhumit', hin: 'ज्ञानाचा तो मळा भुमित', vol: '3', pn: '324' },
    { eng: 'ganga ti jai bhu varun', hin: 'गंगा ती जाई भू वरून', vol: '3', pn: '325' },
    { eng: 'jani janardan santrupe avatarla', hin: 'जनी जनार्दन संतरूपे अवतरला', vol: '3', pn: '326' },
    { eng: 'jay jay ramkrushn hari', hin: 'जय जय रामकृष्ण हरी', vol: '3', pn: '327' },
    { eng: 'is dharatipar dekho bhagavan', hin: 'इस धरतीपर देखो भगवन', vol: '3', pn: '330' },
    { eng: 'jahan tha jana vaha hm', hin: 'जहाँ था जाना वहाँ हम', vol: '3', pn: '331' },
    { eng: 'aj bhavna ke mere ful', hin: 'आज भावना के मेरे फूल', vol: '3', pn: '333' },
    { eng: 'gaun to gaui mai chya', hin: 'गाऊँ तो गाऊई मै क्या', vol: '3', pn: '334' },
    { eng: 'khir bhavani tune to', hin: 'खीर भवानी तुने तो', vol: '3', pn: '335' },
    { eng: 'ambajine bhakt ko apne', hin: 'अंबाजीने भक्त को अपने', vol: '3', pn: '336' },
    { eng: 'kal kareso aj karana', hin: 'कल करेसो आज करना', vol: '3', pn: '337' },
    { eng: 'kalo guruji ek bar mere', hin: 'चलो गुरूजी एक बार मेरे', vol: '3', pn: '339' },
    { eng: 'vo shirdi vo vadi', hin: 'वो शिरडी वो वाडी', vol: '3', pn: '341' },
    { eng: 'koi matlab to hota hai', hin: 'कोई मतलब तो होता है', vol: '3', pn: '343' },

    { eng: 'shivaji teri kripa ho', hin: 'शिवजी तेरी कृपा हो', vol: '3', pn: '344' },
    { eng: 'shivaji dolo na', hin: 'शिवजी डोलो ना', vol: '3', pn: '345' },
    { eng: 'bhajan ka pyasa hai prmatma', hin: 'भजन का प्यासा है परमात्मा', vol: '3', pn: '346' },
    { eng: 'ham aj hai sukh ya dukh me', hin: 'हम आज है सुख या दुख मे', vol: '3', pn: '347' },
    { eng: 'koi gar puche rahate ho', hin: 'कोई गर पूछे रहते हो', vol: '3', pn: '348' },
    { eng: 'tum bin mai hun udas', hin: 'तुम बिन मै हूँ उदास', vol: '3', pn: '349' },
    { eng: 'tum bin to kchu nhi jivanme', hin: 'तुम बीन तो कछु नहि जीवनमे', vol: '3', pn: '350' },
    { eng: 'bhaiyo bhaiyo', hin: 'भाईयो भाईयो', vol: '3', pn: '352' },
    { eng: 'mai parades me rahati hu', hin: 'मैं परदेस में रहती हू', vol: '3', pn: '353' },
    { eng: 'jholi bhar do jholi bhar do', hin: 'झोली भर दो झोली भर दो', vol: '3', pn: '354' },
    { eng: 'chalo sathiyo ek sahara milega', hin: 'चलो साथियो एक सहारा मिलेगा', vol: '3', pn: '355' },
    { eng: 'jisine dekha unako', hin: 'जिसीने देखा उनको', vol: '3', pn: '356' },
    { eng: 'kahna kahun to bhi na mai', hin: 'कहना चाहूँ तो भी ना मै', vol: '3', pn: '358' },
    { eng: 'tarak hai prbhu nam jivan me', hin: 'तारक है प्रभू नाम जीवन मे', vol: '3', pn: '359' },
    { eng: 'bas ek bar mujhe do', hin: 'बस एक बार मुझे दो', vol: '3', pn: '360' },
    { eng: 'aj khushi se dekho ai', hin: 'आज खुशी से देखो आई', vol: '3', pn: '361' },
    { eng: 'sone ka vakt hoke bhi jago', hin: 'सोने का वक्त होके भी जागो', vol: '3', pn: '362' },
    { eng: 'tumse to milate milate', hin: 'तुमसे तो मिलते मिलते', vol: '3', pn: '363' },
    { eng: 'kal ki khabar na aj mujhe', hin: 'कल की खबर ना आज मुझे', vol: '3', pn: '364' },
    { eng: 'tu hi brahma tu hi visnu', hin: 'तू ही ब्रम्हा तू ही विष्णु', vol: '3', pn: '365' },
    { eng: 'rat ho ya din fir bhi', hin: 'रात हो या दिन फिर भी', vol: '3', pn: '366' },
    { eng: 'ab tere kadamo pe meri', hin: 'अब तेरे कदमो पे मेरी', vol: '3', pn: '367' },
    { eng: 'aja aja kanhaiya yamuna ke', hin: 'आजा आजा कन्हैया यमुना के', vol: '3', pn: '368' },
    { eng: 'jahan jahan tu hai guru bhi', hin: 'जहाँ जहाँ तू है गुरू भी', vol: '3', pn: '369' },
    { eng: 'nam harinam harinam radhesham', hin: 'नाम हरिनाम हरिनाम राधेशाम', vol: '3', pn: '370' },

    { eng: 'sochkar sochoo kya socha', hin: 'सोचकर सोचो क्या सोचा', vol: '3', pn: '371' },
    { eng: 'ab raham najar karalo', hin: 'अब रहम नजर करलो', vol: '3', pn: '373' },
    { eng: 'narayan ki lila dekhlo', hin: 'नारायण की लीला देखलो', vol: '3', pn: '374' },
    { eng: 'shari dattaguru bhagavan hamare', hin: 'श्री दत्तगरू भगवान हमारे', vol: '3', pn: '375' },
    { eng: 'pitrupakshat deva hi many kara', hin: 'पितृपक्षात देवा ही मान्य करा', vol: '3', pn: '378' },
    { eng: 'pitarano pitarano pitarano daya kra', hin: 'पितरानो पितरानो पितरानो दया करा', vol: '3', pn: '379' },
    { eng: 'parivaracha karta jiv to jata', hin: 'परिवाराचा कर्ता जीव तो जाता', vol: '3', pn: '380' },
    { eng: 'prasannata tya kanakanat', hin: 'प्रसन्नता त्या कणाकणात', vol: '3', pn: '382' },
    { eng: 'jagadambechi jashi kahani', hin: 'जगदम्बेची जशी कहाणी', vol: '3', pn: '383' },
    { eng: 'kshama kar ai balakas', hin: 'क्षमा कर आई बालकांस', vol: '3', pn: '385' },
    { eng: 'kasht karun gathatos gham', hin: 'कष्ट करुन गाठतोस घाम', vol: '3', pn: '386' },
    { eng: 'thave na malach ki mi', hin: 'ठावे ना मलाच की मी', vol: '3', pn: '388' },
    { eng: 'yere yere chakora ye lavakari', hin: 'येरे येरे चकोरा ये लवकारी', vol: '3', pn: '389' },
    { eng: 'hi pavan bhumi sagar', hin: 'ही पावन भूमी सागर', vol: '3', pn: '390' },
    { eng: 'sukhvitohi dukhvitohi', hin: 'सुखवितोही दुखवितोही', vol: '3', pn: '391' },
    { eng: 'sampale ka kary te', hin: 'सम्पले का कार्य ते', vol: '3', pn: '393' },
    { eng: 'jara sajne savar tujha', hin: 'जरा सजणे सावर तुझा', vol: '3', pn: '394' },
    { eng: 'janjira murud ahe', hin: 'जंजिरा मुरूड आहे', vol: '3', pn: '396' },
    { eng: 'ran pakhara mar bharari', hin: 'रान पाखरा मार भरारी', vol: '3', pn: '397' },
    { eng: 'jaga jaga banghu bhagaini', hin: 'जागा जागा बंघू भगिनी', vol: '3', pn: '398' },
    { eng: 'shripatachya athavaniche', hin: 'श्रीपताच्या आठवणीचे', vol: '3', pn: '399' },

    { eng: 'veda to bhalatach bolat rahi', hin: 'वेडा तो भलतच बोलत राही', vol: '3', pn: '400' },
    { eng: 'khulle nabh purv dishe', hin: 'खुलले नभ पूर्व दिशे', vol: '3', pn: '401' },
    { eng: 'pathi kona sathi', hin: 'पाठी कोणा साठी', vol: '3', pn: '402' },
    { eng: 'adnyani adnyani amhi tar', hin: 'अज्ञानी अज्ञानी आम्ही तर', vol: '3', pn: '403' },
    { eng: 'javal guru paurnimechi ali ghadi', hin: 'जवळ गुरू पौर्णीमेची आली घडी', vol: '3', pn: '405' },
    { eng: 'mi pahiyela ya yoddha', hin: 'मी पाहियेला या योद्धा', vol: '3', pn: '406' },
    { eng: 'sagar sarita dev devta', hin: 'सागर सरिता देव देवता', vol: '3', pn: '408' },
    { eng: 'jhadveli ti ranapakhare', hin: 'झाडवेली ती रानापाखरे', vol: '3', pn: '410' },
    { eng: 'suvarnalanka sujalam sufalam', hin: 'सुवर्णलंका सुजलम् सुफलम्', vol: '3', pn: '411' },
    { eng: 'he tandela bandari bandari vavatal', hin: 'हे तांडेला बंदरी बंदरी वावटल', vol: '3', pn: '412' },
    { eng: 'bhagyvan ho apan sare', hin: 'भाग्यवान हो आपण सारे', vol: '3', pn: '413' },
    { eng: 'marathmolya ladhavayyanche gaje shahar', hin: 'मराठमोळ्या लढवय्यांचे गाजे शहर', vol: '3', pn: '414' },
    { eng: 'dhany majhe pita ni mata', hin: 'धन्य माझे पिता नी माता', vol: '3', pn: '415' },
    { eng: 'dongarchya alyad nadichya palyad', hin: 'डोंगरच्या अल्याड नदीच्या पल्याड', vol: '3', pn: '416' },
    { eng: 'he bhagvanta kar tu chirayu', hin: 'हे भगवंता कर तू चिरायू', vol: '3', pn: '418' },
    { eng: 'vadiloparjit amhi govekar', hin: 'वडिलोपार्जित आम्ही गोवेकर', vol: '3', pn: '421' },
    { eng: 'gajbajlele gokul', hin: 'गजबजलेले गोकुळ', vol: '3', pn: '422' },
    { eng: 'avati bhavati dev ni', hin: 'अवती भवती देव नी', vol: '3', pn: '423' },
    { eng: 'jhale te gele pudhe laksh dyavi', hin: 'झाले ते गेले पुढे लक्ष द्यावी', vol: '3', pn: '424' },
    { eng: 'avati bhavti parvatraga', hin: 'अवती भवती पर्वतरागा', vol: '3', pn: '425' },
    { eng: 'vadiloparjit amhi kutumbi', hin: 'वडिलोपार्जित आम्ही कुटुंबी', vol: '3', pn: '426' },
    { eng: 'anantachya jhadavari', hin: 'अनंताच्या झाडावरी', vol: '3', pn: '428' },
    { eng: 'achanak kashi chamakali jani', hin: 'अचानक कशी चमकली जनी', vol: '3', pn: '429' },
    { eng: 'varshbhrachi seva sarata', hin: 'वर्षभराची सेवा सरता', vol: '3', pn: '430' },
    { eng: 'nrsimh saraswati ni', hin: 'नरसिंह सरस्वती नि', vol: '3', pn: '431' },

    { eng: 'vadta satya vachan mauli', hin: 'वदता सत्य वचन माऊली', vol: '3', pn: '432' },
    { eng: 'pti majha asava ramacha avtar', hin: 'पती माझा असावा रामाचा अवतार', vol: '3', pn: '433' },
    { eng: 'guru maharaj tumha pathishi', hin: 'गुरू महाराज तुम्हा पाठीशी', vol: '3', pn: '434' },
    { eng: 'jo bala jo bala halvito hindola', hin: 'जो बाळा जो बाळा हलवितो हिंदोळा', vol: '3', pn: '436' },
    { eng: 'pran ghenya kal dhavla', hin: 'प्राण घेण्या काळ धावला', vol: '3', pn: '437' },
    { eng: 'tya atmyane deh jhijavla', hin: 'त्या आत्म्याने देह झिजवला', vol: '3', pn: '438' },
    { eng: 'ravirajache hota agaman', hin: 'रविराजाचे होता आगमन', vol: '3', pn: '440' }
];