var p1 = [
    { eng: 'mangal din ale', hin: 'मंगल दिन आले', vol: '1', pn: '2' },
    { eng: 'gan nayaka gaurinandana ganesh ganapati', hin: 'गणनायका गौरीनंदना', vol: '1', pn: '3' },
    { eng: 'nach ganesha nach ganesha', hin: 'नाच गणेशा नाच गणेशा', vol: '1', pn: '4' },
    { eng: 'dhumravarna dhumraketu dhanya lambodara', hin: 'धुम्रवर्ण धूम्रकेतु धन्य लंबोदरा', vol: '1', pn: '5' },
    { eng: 'tuzyachsathi maha ganapati', hin: 'तुझ्याचसाठी महागणपती', vol: '1', pn: '6' },
    { eng: 'managalmurti tuziya pudhati', hin: 'मंगलमूर्ती तुझिया पुढती', vol: '1', pn: '7' },
    { eng: 'mahaganapati daya kari', hin: 'महागणपती दया करी', vol: '1', pn: '8' },
    { eng: 'he moreshwara he mayureshwara', hin: 'हे मोरेश्वर हे मयुरेश्वर', vol: '1', pn: '9' },
    { eng: 'pratham stavan karato', hin: 'प्रथम स्तवन करतो', vol: '1', pn: '10' },
    { eng: 'shendur malavati', hin: 'शेंदूर मळवटी', vol: '1', pn: '11' },
    { eng: 'he ganadhishare vandan', hin: 'हे गणाधीशारे वंदन', vol: '1', pn: '12' },
    { eng: 'bappa moraya', hin: 'बाप्पा मोऱया', vol: '1', pn: '13' },
    { eng: 'om gan ganapataye namah', hin: 'ॐ गं गणपतये नमः', vol: '1', pn: '14' },
    { eng: 'ganadhishachi aj ase', hin: 'गणाधीशाची आज असे', vol: '1', pn: '15' },
    { eng: 'mangalam ganeshwara', hin: 'मंगलम गणेश्वरा', vol: '1', pn: '16' },
    { eng: 'nityam shubham chintanam', hin: 'नित्यं शुभम चिंतनं', vol: '1', pn: '18' },
    { eng: 'bhav bhukene swagat karito', hin: 'भाव भुकेने स्वागत करितो', vol: '1', pn: '20' },
    { eng: 'namo namo namo namo', hin: 'नमो नमो नमो नमो', vol: '1', pn: '22' },
    { eng: 'ekdanta girijakumara', hin: 'एकदंता गिरिजाकुमरा', vol: '1', pn: '23' },
    { eng: 'gan nayaka gaurinandana kashil', hin: 'गणनायका गौरीनंदना - काशीळ', vol: '1', pn: '24' },
    { eng: 'dnyani jananna muni jananna', hin: 'ज्ञानी जनांना मुनि जनांना', vol: '1', pn: '25' },
    { eng: 'gajanana ye re', hin: 'गजानना ये रे', vol: '1', pn: '26' },
    { eng: 'ale ganaraya ale devaraya', hin: 'आले गणराया आले देवराया', vol: '1', pn: '27' },
    { eng: 'ganapati bappa moraya', hin: 'गणपती बाप्पा मोऱया', vol: '1', pn: '28' },
    { eng: 'adbhut kar karani', hin: 'अदभूत कर करणी', vol: '1', pn: '29' },
    { eng: 'he gajanana devagana', hin: 'हे गजानना देवागणा', vol: '1', pn: '30' },
    { eng: 'tuj pranam re mangalmurti', hin: 'तुज प्रणाम रे मंगलमूर्ती', vol: '1', pn: '31' },
    { eng: 'mangal divasi mangal charani', hin: 'मंगल दिवशी मंगल चरणी', vol: '1', pn: '32' },
    { eng: 'ughade asata donhi dole', hin: 'उघडे असता दोन्ही डोळे', vol: '1', pn: '34' },
    { eng: 'prabhu datta majha kadhi', hin: 'प्रभू दत्त माझा कधी', vol: '1', pn: '35' },
    { eng: 'datta bhajan karnar', hin: 'दत्त भजन करणार', vol: '1', pn: '36' },
    { eng: 'datta maybap majha sakha', hin: 'दत्त मायबाप माझा', vol: '1', pn: '37' },
    { eng: 'saritechya kathi kuni', hin: 'सरितेच्या काठी कुणी', vol: '1', pn: '38' },
    { eng: 'kalchakra chalu ahe', hin: 'कालचक्र चालू आहे', vol: '1', pn: '39' },
    { eng: 'maj mothepan deu', hin: 'मज मोठेपण देऊ नको', vol: '1', pn: '40' },
    { eng: 'om datta narayan', hin: 'ॐ दत्त नारायण', vol: '1', pn: '41' },
    { eng: 'lavishi vilamb ka re', hin: 'लाविशी विलंब का रे', vol: '1', pn: '42' },
    { eng: 'zunjumunju jahle ata junju munj munz', hin: 'झुंजूमुंजू जाहले आता', vol: '1', pn: '43' },
    { eng: 'tuzya sangatit jagu de', hin: 'तुझ्या संगतीत जगू दे', vol: '1', pn: '44' },
    { eng: 'jhoka deto tuj parameshwara', hin: 'झोका देतो तुज परमेश्वरा', vol: '1', pn: '45' },
    { eng: 'chaitanya sadguru ase mauli', hin: 'चैतन्य सद्गुरू असे माउली', vol: '1', pn: '46' },
    { eng: 'bhatakun bhatakun shunya shevati', hin: 'भटकून भटकून शून्य शेवटी', vol: '1', pn: '47' },
    { eng: 'sang re gururaya', hin: 'सांग रे गुरुराया', vol: '1', pn: '48' },
    { eng: 'kon mhanato datta gela', hin: 'कोण म्हणतो दत्त गेला', vol: '1', pn: '49' },
    { eng: 'datta avadhuta', hin: 'दत्ता अवधूता', vol: '1', pn: '50' },
    { eng: 'vallabha shripad shrivallabha', hin: 'वल्लभा श्रीपाद श्रीवल्लभा', vol: '1', pn: '51' },
    { eng: 'avadhuta majha yogi dattaraja', hin: 'अवधूत माझा योगी दत्तराजा', vol: '1', pn: '52' },
    { eng: 'akkalkot guru maharaj', hin: 'अक्कलकोट गुरु महाराज', vol: '1', pn: '53' },
    { eng: 'dattaname dola janaho gajar kara', hin: 'दत्तनामे डोळा जनहो गजर करा', vol: '1', pn: '54' },
    { eng: 'sadgurunni kathile hrudayat', hin: 'सद्गुरूंनी कथिले हृद्गत', vol: '1', pn: '55' },
    { eng: 'panchgangevari pushpasan mandoni', hin: 'पंचगंगेवरी पुष्पांसन मांडोनी', vol: '1', pn: '56' },
    { eng: 'digambara jay digambara', hin: 'दिगंबरा जय दिगंबरा', vol: '1', pn: '58' },
    { eng: 'shaligram majha datta', hin: 'शाळिग्राम माझा दत्त', vol: '1', pn: '59' },
    { eng: 'datta ale majhya dwari', hin: 'दत्त आले माझ्या द्वारी', vol: '1', pn: '61' },
    { eng: 'shri guruncha sadguni shishya', hin: 'श्रीगुरुंचा सद्गुणी शिष्य', vol: '1', pn: '62' },
    { eng: 'thamblase chala', hin: 'थांबलासे चाळा', vol: '1', pn: '64' },
    { eng: 'jay jay digambar adhar', hin: 'जय जय दिगंबर आधार', vol: '1', pn: '65' },
    { eng: 'deva narsimh raja dattatreya', hin: 'देवा नरसिंह राजा दत्तात्रेया', vol: '1', pn: '66' },
    { eng: 'pratimetuni bol ba', hin: 'प्रतिमेतूनी बोल बा', vol: '1', pn: '67' },
    { eng: 'ardhi ratra ata sampali', hin: 'अर्धी रात्र आता संपली', vol: '1', pn: '68' },
    { eng: 'rahi tithe shripad shrivallabh', hin: 'राही तिथे श्रीपाद श्रीवल्लभ', vol: '1', pn: '70' },
    { eng: 'tya gard jhad zad jhad veli', hin: 'त्या गर्द झाड वेली', vol: '1', pn: '71' },
    { eng: 'harihara digambara', hin: 'हरिहरा दिगंबरा', vol: '1', pn: '73' },
    { eng: 'jai jai sadguru dattaguru', hin: 'जय जय सद्गुरू दत्तगुरु', vol: '1', pn: '74' },
    { eng: 'pujuya vanduya', hin: 'पुजूया वंदुया', vol: '1', pn: '75' },
    { eng: 'sadguru dattaguru', hin: 'सद्गुरू दत्तगुरु', vol: '1', pn: '76' },
    { eng: 'bhimatati parnakuti', hin: 'भीमातटी पर्णकुटी', vol: '1', pn: '77' },
    { eng: 'jo jo re dattaraja', hin: 'जो जो रे दत्तराजा', vol: '1', pn: '78' },
    { eng: 'om datta om datta vache', hin: 'ॐदत्त ॐदत्त वाचे', vol: '1', pn: '79' },
    { eng: 'bala narahari paha', hin: 'बाळा नरहरी पाहा', vol: '1', pn: '80' },
    { eng: 'adiguru paramguru paratpar guru', hin: 'आदिगुरू परमगुरु परात्परगुरू', vol: '1', pn: '81' },
    { eng: 'he swami olakhiti satvar', hin: 'हे स्वामी ओळखिती सत्त्वर', vol: '1', pn: '82' },
    { eng: 'vajate manjiri dattamandiri', hin: 'वाजते मंजिरी दत्तमंदिरीं', vol: '1', pn: '83' },
    { eng: 'soniyachya palanyala motiyachi dori', hin: 'सोनियाच्या पाळण्याला मोतियांची दोरी', vol: '1', pn: '84' },
    { eng: 'to nesala katis pitambar', hin: 'तो नेसला जातीस पितांबर', vol: '1', pn: '85' },
    { eng: 'shriguru utha utha lavakari', hin: 'श्रीगुरु उठा उठा लवकरी', vol: '1', pn: '86' },
    { eng: 'om datta gururaya tula ghe manacha mujara', hin: 'ॐ दत्त गुरुराया तुला घे मानाचा मुजरा', vol: '1', pn: '87' },
    { eng: 'shri kshetra ganagapuri sushobhit', hin: 'श्रीक्षेत्र गाणगापुरी सुशोभित', vol: '1', pn: '88' },
    { eng: 'brahma harihar dhave hakevar', hin: 'ब्रह्म हरिहर धावे हाकेवर', vol: '1', pn: '89' },
    { eng: 'nilambarache te chhat varati', hin: 'निलंबराचे ते छत वरती', vol: '1', pn: '90' },
    { eng: 'gurudev majhe bhagvant', hin: 'गुरुदेव माझे भगवंत', vol: '1', pn: '91' },
    { eng: 'bij bhuvar periyele', hin: 'बीज भूवर पेरियेले', vol: '1', pn: '92' },
    { eng: 'pragat rupane amhi nighalo', hin: 'प्रगट रूपाने आम्ही निघालो', vol: '1', pn: '93' },
    { eng: 'karata harata digambar', hin: 'करता हारता दिगंबर', vol: '1', pn: '94' },
    { eng: 'shrigurunni tya shalet maj ghatle', hin: 'श्रीगुरूंनी त्या शाळेत मज घातले', vol: '1', pn: '95' },
    { eng: 'don charan shire tin prabhula', hin: 'दोन चरण शिरे तीन प्रभूला', vol: '1', pn: '96' },
    { eng: 'datta digambar kati pitambar', hin: 'दत्त दिगंबर कटी पितांबर', vol: '1', pn: '97' },
    { eng: 'brahma shiva donhi baju', hin: 'ब्रह्मा शिव दोन्ही बाजू', vol: '1', pn: '98' },
    { eng: 'sage soyare na kuni', hin: 'सगे सोयरे ना कुणी', vol: '1', pn: '99' },
    { eng: 'dharmadand tya kari dharila', hin: 'धर्मदंड त्या करी धरिला', vol: '1', pn: '100' },
    { eng: 'om datta omdatta premane bola', hin: 'ॐ दत्त ॐ दत्त प्रेमाने बोला', vol: '1', pn: '102' },
    { eng: 'gangechya kathavar dongar mathyavar', hin: 'गंगेच्या काठावर डोंगर माथ्यावर', vol: '1', pn: '104' },
    { eng: 'bolavite kashi', hin: 'बोलविते काशी', vol: '1', pn: '106' },
    { eng: 'jagatoddhara shrimurti', hin: 'जगतोद्धारा श्रीमूर्ती', vol: '1', pn: '107' },
    { eng: 'gramvasi ani aptaishth', hin: 'ग्रामवासी आणि आप्तईष्ट', vol: '1', pn: '108' },
    { eng: 'paniyat snan kari narayan', hin: 'पाणियात स्नान करी नारायण', vol: '1', pn: '109' },
    { eng: 'shiv dhari jayache charan', hin: 'शिव धरी जयाचे चरण', vol: '1', pn: '110' },
    { eng: 'datta majha jagojagi', hin: 'दत्त माझा जागोजागी', vol: '1', pn: '112' },
    { eng: 'om bramh vishnu maheshwar ubhar tu bhuvar', hin: 'ॐ ब्रह्म विष्णू महेश्वर उभा तू भूवर', vol: '1', pn: '113' },
    { eng: 'dig dig dig dig disha ni ambar', hin: 'दिग् दिग् दिग् दिग् दिशा नि अंबर', vol: '1', pn: '114' },
    { eng: 'nisarg dole anandat', hin: 'निसर्ग डोले आनंदात', vol: '1', pn: '117' },
    { eng: 'yativaranni tya vipracha', hin: 'यतिवरांनी त्या विप्राचा', vol: '1', pn: '118' },
    { eng: 'sharan sharan om datta raja', hin: 'शरण शरण ॐ दत्त राजा', vol: '1', pn: '119' },
    { eng: 'dattatrayane janm ghetala', hin: 'दत्तात्रयाने जन्म घेतला', vol: '1', pn: '120' },
    { eng: 'charanamrutane mrutdehi tya', hin: 'चरणामृताने मृतदेही त्या', vol: '1', pn: '121' },
    { eng: 'dev bhaktihuni thor gurubhakti', hin: 'देवभक्तिहुनी थोर गुरुभक्ति', vol: '1', pn: '122' },
    { eng: 'namdharakala darshan milale', hin: 'नामधारकाला दर्शन मिळाले', vol: '1', pn: '123' },
    { eng: 'pimpalachya zadakhali jhada', hin: 'पिंपळाच्या झाडाखाली', vol: '1', pn: '124' },
    { eng: 'vanjh mahile vardhakyat', hin: 'वांझ महिले वार्धक्यात', vol: '1', pn: '125' },
    { eng: 'tya tirthayatre sobatachya shishyana', hin: 'त्या तीर्थयात्रे सोबतच्या शिष्याना', vol: '1', pn: '126' },
    { eng: 'jay jay jay he dattadigambar', hin: 'जय जय जय हे दत्तदिगंबर', vol: '1', pn: '127' },
    { eng: 'bhima amarajechya kathi', hin: 'भीमा अमरजेच्या काठी', vol: '1', pn: '128' },
    { eng: 'sampavun avatar jata', hin: 'संपवून अवतार जाता', vol: '1', pn: '129' },
    { eng: 'hi karm bhumi amuchi pavitra', hin: 'ही कर्म भूमी अमुची पवित्र', vol: '1', pn: '130' },
    { eng: 'gandharvapuri ya jamala sagala', hin: 'गंधर्वपुरी या जमला सगळा', vol: '1', pn: '133' },
    { eng: 'madhavsut ani atrisutane', hin: 'माधवसुत आणि अत्रिसुताने', vol: '1', pn: '134' },
    { eng: 'ya lekaranno dattaichya angani', hin: 'या लेकरांनो दत्ताईच्या अंगणी', vol: '1', pn: '135' },
    { eng: 'dhanya ase avatar', hin: 'धन्य असे अवतार', vol: '1', pn: '136' },
    { eng: 'pranam ha atrinandana', hin: 'प्रणाम हा अत्रीनंदना', vol: '1', pn: '138' },
    { eng: 'sadguru chi lila ghadi ghadi', hin: 'सद्गुरू ची लीला घडी घडी', vol: '1', pn: '139' },
    { eng: 'avicharane bhalate salate', hin: 'अविचाराने भलते सलते', vol: '1', pn: '140' },
    { eng: 'ti bhima amaraja sangam tyancha', hin: 'ती भीमा अमरजा संगम त्यांचा', vol: '1', pn: '141' },
    { eng: 'kalpavruksh audumbar to detase', hin: 'कल्पवृक्ष औदुंबर तो देतसे', vol: '1', pn: '142' },
    { eng: 'tujhi dattai', hin: 'तुझी दत्ताई', vol: '1', pn: '143' },
    { eng: 'rahi tithe shripad shrivallabh', hin: 'राही तिथे श्रीपाद श्रीवल्लभ', vol: '1', pn: '144' },
    { eng: 'ghar majhe te kaularu', hin: 'घर माझे ते कौलारू', vol: '1', pn: '145' },
    { eng: 'gavakaryano gavachi sampali', hin: 'गावकर्यानो गावाची संपली', vol: '1', pn: '146' },
    { eng: 'he digambara digambara', hin: 'हे दिगंबरा दिगंबरा', vol: '1', pn: '147' },
    { eng: 'ha jiv jivani shriguru', hin: 'हा जीव जीवनी श्रीगुरु', vol: '1', pn: '148' },
    { eng: 'kadhi kadhi kaivari dole', hin: 'कधी कधी कैवारी डोले', vol: '1', pn: '150' },
    { eng: 'dev narahari pahiyale', hin: 'देव नरहरी पाहियले', vol: '1', pn: '151' },
    { eng: 'dam dam damaru vajat ahe', hin: 'डम डम डमरु वाजत आहे', vol: '1', pn: '153' },
    { eng: 'hari om hari om', hin: 'हरि ओम हरि ओम', vol: '1', pn: '154' },
    { eng: 'shankara mi kailasi pahile', hin: 'शंकरा मी कैलासी पाहिले', vol: '1', pn: '156' },
    { eng: 'bam bhole bam bhole shankaraji', hin: 'बम भोले बम भोले शंकरजी', vol: '1', pn: '157' },
    { eng: 'shiv nachati kailashi', hin: 'शिव नाचती कैलाशी', vol: '1', pn: '158' },
    { eng: 'dhavat ye tripurari', hin: 'धावत ये त्रिपुरारी', vol: '1', pn: '159' },
    { eng: 'gangadhara shiva', hin: 'गंगाधरा शिवा', vol: '1', pn: '160' },
    { eng: 'gauri hara tripurari bholya shiva', hin: 'गौरी हरा त्रिपुरारी भोळ्या शिवा', vol: '1', pn: '161' },
    { eng: 'svayambhu shivashambhuche shivaling te pahile', hin: 'स्वयंभू शिवशंभुचे शिवलिंग ते पाहिले', vol: '1', pn: '162' },
    { eng: 'duravar tya shikharavari trishul damarudhari', hin: 'दूरवर त्या शिखरावरी त्रिशूळ डमरूधारी', vol: '1', pn: '163' },
    { eng: 'kailasapati shivashankara', hin: 'कैलासपती शिवशंकरा', vol: '1', pn: '164' },
    { eng: 'he sadashiva gangadhara parvatichya vara', hin: 'हे सदाशिवा गंगाधरा पार्वतीच्या वरा', vol: '1', pn: '166' },
    { eng: 'shankara shankara shankara shambhuji shankara', hin: 'शंकरा शंकरा शंकरा शंभूजी शंकरा', vol: '1', pn: '167' },
    { eng: 'ishwara samip sparshile jalat', hin: 'ईश्वरा समीप स्पर्शिले जलात', vol: '1', pn: '168' },
    { eng: 'tuj koti koti pranam gangadhara', hin: 'तुज कोटी कोटी प्रणाम गंगाधरा', vol: '1', pn: '169' },
    { eng: 'om datta majhe aradhya daivat', hin: 'ॐ दत्त माझे आराध्य दैवत', vol: '1', pn: '170' },
    { eng: 'shiv shankara karunakara', hin: 'शिव शंकरा करुणाकरा', vol: '1', pn: '171' },
    { eng: 'dol jara dol hasuni ge', hin: 'डोल जरा डोल हासुनी गे', vol: '1', pn: '174' },
    { eng: 'mahalakshmi mahasarasvati mahakalike', hin: 'महालक्ष्मी महासरस्वती महाकालिके', vol: '1', pn: '175' },
    { eng: 'ambabai durga ai', hin: 'अंबाबाई दुर्गा आई', vol: '1', pn: '176' },
    { eng: 'bhugarbhat vas karoni', hin: 'भुगर्भात वास करोनी', vol: '1', pn: '177' },
    { eng: 'bramha vishnu rudra sangati', hin: 'बह्म विष्णू रूद्र सांगती', vol: '1', pn: '178' },
    { eng: 'jay jay ambe jay ambe', hin: 'जय जय अंबे जय अंबे', vol: '1', pn: '179' },
    { eng: 'shir namavito mi ambe charanavari', hin: 'शिर नमवितो मी अंबे चरणावरी', vol: '1', pn: '180' },
    { eng: 'devi saptashrngi prarthito tula mi', hin: 'देवी सप्तशृंगी प्रार्थितो तुला मी', vol: '1', pn: '181' },
    { eng: 'shaktidevata tu durge dyavi', hin: 'शक्तिदेवता तू दुर्गे द्यावी', vol: '1', pn: '182' },
    { eng: 'om em him klim chamundeshvari', hin: 'ॐ ऐम ऐं ऱ्हीं क्लीं चामुडेश्वरी', vol: '1', pn: '183' },
    { eng: 'he jay santoshi mata', hin: 'हे जय संतोषी माता', vol: '1', pn: '186' },
    { eng: 'kshanabhar kari agaman', hin: 'क्षणभर करी आगमन', vol: '1', pn: '187' },
    { eng: 'majhya santoshi matela', hin: 'माझ्या संतोषी मातेला', vol: '1', pn: '188' },
    { eng: 'devi karu kay bare mi ata', hin: 'देवी करू काय बरे मी आता', vol: '1', pn: '189' },
    { eng: 'tup roti mile sat bala', hin: 'तुपरोटी मिळे सात बाळा', vol: '1', pn: '190' },
    { eng: 'ovalu arati mata santoshi', hin: 'ओवाळू आरती माता संतोषी', vol: '1', pn: '191' },
    { eng: 'kadhi bhet deshi ya pamarashi', hin: 'कधी भेट देशी या पामराशी', vol: '1', pn: '192' },
    { eng: 'paradeshi pati te gele majhe nighuni', hin: 'परदेशी पती ते गेले माझे निघुनी', vol: '1', pn: '193' },
    { eng: 'jay mahalakshmi dhav pav', hin: 'जय महालक्ष्मी संतोषी धाव पाव', vol: '1', pn: '194' },
    { eng: 'ahe ghari bharpur te kay kamacha', hin: 'आहे घरी भरपूर ते काय कामाच', vol: '1', pn: '195' },
    { eng: 'bhajanat ahe godi', hin: 'भजनांत आहे गोडी', vol: '1', pn: '196' },
    { eng: 'jauni aj dharuya charan', hin: 'जाऊनी आज धरूया चरण', vol: '1', pn: '197' },
    { eng: 'santoshi devi santoshi devi', hin: 'संतोषी देवी, संतोषी देवी', vol: '1', pn: '198' },
    { eng: 'gharagharatun nari tujhe vrat karati', hin: 'घराघरातून नारी तुझे व्रत करती', vol: '1', pn: '199' },
    { eng: 'sarya jagachi santoshi mata', hin: 'साऱ्या जगावी संतोषी माता', vol: '1', pn: '200' },
    { eng: 'niyam vratache dhyani dharave', hin: 'नियम व्रताचे ध्यानी धरावे', vol: '1', pn: '201' },
    { eng: 'bhajanat bahu ramato mi', hin: 'भजनात बहू रमतो मी', vol: '1', pn: '202' },
    { eng: 'tu mahalakshmi jagat mata', hin: 'तू महालक्ष्मी जगत माता', vol: '1', pn: '203' },
    { eng: 'dete anand majha manashi', hin: 'देते आनंद माझा मनाशी', vol: '1', pn: '204' },
    { eng: 'jhala bai harsh majhya aj', hin: 'झाला बाई हर्ष माझा आज', vol: '1', pn: '205' },
    { eng: 'nitya kara he vrat abalanno', hin: 'नित्य करा हे व्रत अबलांनो', vol: '1', pn: '206' },
    { eng: 'ya ga sayanno ya ga sayanno', hin: 'या ग सयानो या ग आयानो', vol: '1', pn: '207' },
    { eng: 'dena dena ai mala tu adhar', hin: 'देना देना आई मला तू आधार', vol: '1', pn: '208' },
    { eng: 'karu ya udo udo ambabaicha', hin: 'करू या ऊदो उदो अंबाबाईचा', vol: '1', pn: '209' },
    { eng: 'sugandh sumanancha sutala', hin: 'सुगंध सुमनाचा सुटला', vol: '1', pn: '210' },
    { eng: 'he kuladevi tuj vandana', hin: 'हे कुळदेवी तुज वंदना', vol: '1', pn: '211' },
    { eng: 'koli dada hodi ne paialatiri', hin: 'कोळी दादा होडी ने पैलतीरी', vol: '1', pn: '212' },
    { eng: 'om bhagavati namastute', hin: 'ॐ भगवती नमस्तुते', vol: '1', pn: '213' },
    { eng: 'udo ge ambai udo ge ambai', hin: 'उदो गे अंबाई उदो उदो गे अंबाई', vol: '1', pn: '214' },
    { eng: 'gayatri devi sahavas tuza', hin: 'गायत्री देवी सहवास तुझा असे', vol: '1', pn: '215' },
    { eng: 'ya dasala tuch adhar', hin: 'या दासाला तूच आधार', vol: '1', pn: '216' },
    { eng: 'ai ghadi ghadi tujhi athavan hote', hin: 'आई घडी घडी तुझी आठवण होते', vol: '1', pn: '217' },
    { eng: 'shantadurga tu kavalyachi', hin: 'शंतादुर्गा तू कवळ्याची', vol: '1', pn: '218' },
    { eng: 'te vishnu shiv hya vasundharevar', hin: 'ते विष्णू शिव ह्या वसुंधरेवर', vol: '1', pn: '219' },
    { eng: 'chamunda shikhari vartale naval', hin: 'चामुंडा शिखरी वर्तले नवल', vol: '1', pn: '220' },
    { eng: 'gato jari mi na rag thave', hin: 'गातो जरी मी ना राग ठावे', vol: '1', pn: '221' },
    { eng: 'he bhagavati kar ya janmi mam uddhar', hin: 'हे भगवती कर या जन्मी मम उध्दार', vol: '1', pn: '222' },
    { eng: 'dole majha puranjan', hin: 'डोले माझा पुरंजन', vol: '1', pn: '223' },
    { eng: 'shaktinusar seva ruju vhavi', hin: 'शक्तिनुसार सेवा रूजु व्हावी', vol: '1', pn: '224' },
    { eng: 'mukut shiravar vina kari', hin: 'मुकुट शिरावर विणा करी', vol: '1', pn: '225' },
    { eng: 'jay matadi jay ambaji', hin: 'जय मातादी जय अंबाजी', vol: '1', pn: '226' },
    { eng: 'shaktidevi tula vandana', hin: 'शक्तिदेवी तुला वंदना', vol: '1', pn: '227' },
    { eng: 'vivanchana ya nij antarichya', hin: 'विवंचना या निज अंतरीच्या', vol: '1', pn: '228' },
    { eng: 'he bhagavati jan pujiti', hin: 'हे भगवती जन पूजिती', vol: '1', pn: '229' },
    { eng: 'ghadi ghadi vate mate darshan dyave', hin: 'घडी घडी वाटे माते दर्शन द्यावे', vol: '1', pn: '230' },
    { eng: 'jagrut ahe ti vishwachi mata', hin: 'जागृत आहे ती विश्वाची माता', vol: '1', pn: '231' },
    { eng: 'vishnu maye saundarya nilaye', hin: 'विष्णू माये सौंदर्य निलये', vol: '1', pn: '232' },
    { eng: 'mata vase mandiri', hin: 'माता वसे मंदिरी', vol: '1', pn: '233' },
    { eng: 'atulya shakti apar kirti', hin: 'अतुल्य शक्ति अपार किर्ती', vol: '1', pn: '234' },
    { eng: 'majhya aicha bharato darbar', hin: 'माझ्या आईचा भरतो दरबार', vol: '1', pn: '235' },
    { eng: 'jagat janni adimaya tu devi', hin: 'जगत् जननी आदिमाया तू देवी', vol: '1', pn: '236' },
    { eng: 'santoshi matechi yaho karuya', hin: 'संतोषी मातेची याहो करुया', vol: '1', pn: '238' },
    { eng: 'pidhya pidhayanchi tu rakhavali', hin: 'पिढया पिढयांची तू रखवाली', vol: '1', pn: '239' },
    { eng: 'pran ghena kal dhavala', hin: 'प्राण घेण्या काळ धावला', vol: '1', pn: '240' },
    { eng: 'jate santoshichya mandiri', hin: 'जाते संतोषीच्या मंदिरी', vol: '1', pn: '241' },
    { eng: 'dev jagajethi', hin: 'देव जगजेठी', vol: '1', pn: '244' },
    { eng: 'polisat jauniya keli takrar', hin: 'पोलिसात जाऊनिया केली तक्रार', vol: '1', pn: '245' },
    { eng: 'pandharapuracha vithoba raja', hin: 'पंढरपूरचा विठोबा राजा', vol: '1', pn: '246' },
    { eng: 'nighali vari pandharapura', hin: 'निघाली वारी पंढरपूरा', vol: '1', pn: '247' },
    { eng: 'nadi vahe khalkhal', hin: 'नदी वाहे खळखळ', vol: '1', pn: '249' },
    { eng: 'rama krushn hari rama krsuhn hari', hin: 'रामकृष्ण हरि रामकृष्ण हरि', vol: '1', pn: '250' },
    { eng: 'te pavan charan dharu', hin: 'ते पावन चरण धरु', vol: '1', pn: '251' },
    { eng: 'pandharichya pandurang as purati jahali', hin: 'पंढरीच्या पांडुरंग आस पुरती जाहली', vol: '1', pn: '252' },
    { eng: 'pandharapurakar panduranga aj tula bahu', hin: 'पंढरपूरकर पांडुरंगा आज तुला बहु', vol: '1', pn: '253' },
    { eng: 'viththal viththal nam te god', hin: 'विठ्ठल विठ्ठल नाम ते गोड', vol: '1', pn: '254' },
    { eng: 'viththal viththala tujhi drusht kadhate', hin: 'विठ्ठल विठ्ठला तुझी टृष्ट काढते', vol: '1', pn: '255' },
    { eng: 'aj karamena jhale mala', hin: 'आज करमेना झाले मला', vol: '1', pn: '257' },
    { eng: 'kashala jau mi durdur', hin: 'कशाला जाऊ मी दूरदूर', vol: '1', pn: '258' },
    { eng: 'patali khun antari', hin: 'पटली खूण अंतरी', vol: '1', pn: '259' },
    { eng: 'hari ghadavito hari bighadato', hin: 'हरि घडवितो हरि बिघडतो', vol: '1', pn: '260' },
    { eng: 'pandharit dang rangato abhang', hin: 'पंढरीत दंग रंगतो अभंग', vol: '1', pn: '262' },
    { eng: 'govinda re rama krushn hari', hin: 'गोविंदा रे रामकृष्ण हरि', vol: '1', pn: '263' },
    { eng: 'viththala dhanya ti pandhari', hin: 'विठ्ठला धन्य ती पंढरी', vol: '1', pn: '264' },
    { eng: 'bhaj rama krushn hari', hin: 'भज रामकृष्ण हरि', vol: '1', pn: '265' },
    { eng: 'panduranga jagajethi pandharichya patala', hin: 'पांडुरंगा जगजेठी पंढरीच्या पाटला', vol: '1', pn: '266' },
    { eng: 'hank tujala marita mi dhav re', hin: 'हाक तुजला मारीता मी धाव रे', vol: '1', pn: '267' },
    { eng: 'sasar viththal maher viththal', hin: 'सासर विठ्ठल माहेर विठ्ठल', vol: '1', pn: '268' },
    { eng: 'don vitanchi mahima mothi', hin: 'दोन विटांची महिमा मोठी', vol: '1', pn: '269' },
    { eng: 'rakhumai pahili vajali bangadi', hin: 'रखुमाई पाहिली वाजली बांगडी', vol: '1', pn: '271' },
    { eng: 'kela janasi manacha jhopala', hin: 'केला जनासी मनाचा झोपाळा', vol: '1', pn: '272' },
    { eng: 'pandharicha raja shrihari mandirat nahi', hin: 'पंढरीचा राजा श्रीहरि मंदिरात नाही', vol: '1', pn: '273' },
    { eng: 'keshava re madhava tujha namat', hin: 'केशवा रे माधवा तुझा नामात', vol: '1', pn: '275' },
    { eng: 'tukacha viththal chokhacha viththal', hin: 'तुकाचा विठ्ठल चोखाचा विठ्ठल', vol: '1', pn: '276' },
    { eng: 'rav rank anandat bolati abhang', hin: 'राव रंक आनंदात बोलती अभंग', vol: '1', pn: '277' },
    { eng: 'pandharapuracha vithoba raja', hin: 'पंढरपूरचा विठोबा राजा', vol: '1', pn: '278' },
    { eng: 'gati jan te nachati vajatase dholaki', hin: 'गाती जन ते नाचती वाजतसे ढोलकी', vol: '1', pn: '279' },
    { eng: 'vina chipalaya tya dur vajatat', hin: 'विणा चिपळया त्या दूर वाजतात', vol: '1', pn: '280' },
    { eng: 'tari chandrabhaga ubha pandurang', hin: 'तारी चंद्राभागा उभा पांडुरंग', vol: '1', pn: '281' },
    { eng: 'chandrabhage tiri vas viththalacha', hin: 'चंद्रभागे तीरी वास विठ्ठलाचा', vol: '1', pn: '282' },
    { eng: 'pandurangachi tethe vase pandhari', hin: 'पांडूरंगाची तेथे वसे पंढरी', vol: '1', pn: '283' },
    { eng: 'panduragachya name dangali mandali', hin: 'पांडूरंगाच्या नामे दंगली मंडळी', vol: '1', pn: '285' },
    { eng: 'viththal pandharit pandhari antarat', hin: 'विठ्ठल पंढरीत पंढरी अंतरात', vol: '1', pn: '286' },
    { eng: 'vitevari dole dole pandurang', hin: 'विटेवरी डोले डोले पांडुरंग', vol: '1', pn: '287' },
    { eng: 'dhanya panduranga dhanya panduranga', hin: 'धन्य पांडुरंगा धन्य पांडुरंगा', vol: '1', pn: '288' },
    { eng: 'jay jay viththale viththale rakhumai', hin: 'जय जय विठ्ठले विठ्ठले रखुमाई', vol: '1', pn: '289' },
    { eng: 'sakha rahe pandharit sakhu sasarat', hin: 'सखा राहे पंढरीत सखू सासरात', vol: '1', pn: '290' },
    { eng: 'jithe pahu tithe dise to shrirang', hin: 'जिथे पाहु तिथे दिसे तो श्रीरंग', vol: '1', pn: '291' },
    { eng: 'to shrihari shrihari shrihari pandharichi vat', hin: 'तो श्रीहरि श्रीहरि श्रीहरि पंढरीची वाट', vol: '1', pn: '292' },
    { eng: 'yuge aththavis ubhi vite viththal mauli', hin: 'युगे अठ्ठावीस उभी विटे विठ्ठल माऊली', vol: '1', pn: '293' },
    { eng: 'bhuka bhakt viththalacha viththal bhuka bhaktacha', hin: 'भुका भक्त विठ्ठलाचा विठ्ठल भुका भक्ताचा', vol: '1', pn: '294' },
    { eng: 'bare viththal kasa karu sansar mi', hin: 'बारे विठ्ठल कसा करु संसार मी', vol: '1', pn: '295' },
    { eng: 'kay chale jagavar', hin: 'काय चाले जगावर', vol: '1', pn: '297' },
    { eng: 'panduranga dhanya tujhi re ti lila', hin: 'पांडुरंगा धन्य तुझी रे ती लिला', vol: '1', pn: '298' },
    { eng: 'tribhuvanat dhvani umatala viththal viththal', hin: 'त्रिभूवनात ध्वनी उमटला विठ्ठल विठ्ठल', vol: '1', pn: '299' },
    { eng: 'nyayadhish viththal sant te vakil arj', hin: 'न्यायाधीश विठ्ठल संत ते वकील अर्ज', vol: '1', pn: '300' },
    { eng: 'he jagajethi may bap tu re bandhu', hin: 'हे जगजेठी माय बाप तू रे बंधू', vol: '1', pn: '301' },
    { eng: 'mamanji dhariti kapali hat', hin: 'मामंजी धरीती कपाळी हात', vol: '1', pn: '302' },
    { eng: 'majhiya manatale tu vichar janashi', hin: 'माझिया मनातले तू विचार जाणशी', vol: '1', pn: '304' },
    { eng: 'vad mukhe mana govind govind', hin: 'वद मुखे मना गोविंद गोविंद', vol: '1', pn: '305' },
    { eng: 'charani bhagavati bhagvatichya aise', hin: 'चरणी भगवती भगवतीच्या ऐसे', vol: '1', pn: '306' },
    { eng: 'jayamule vithu uma vitevar', hin: 'जयामुळे विठू उमा विटेवर', vol: '1', pn: '307' },
    { eng: 'majha viththal viththal shri hari', hin: 'माझा विठ्ठल विठ्ठल श्री हरी', vol: '1', pn: '308' },
    { eng: 'gav pandhari pandhari majhe pandhari', hin: 'गाव पंढरी पंढरी माझे पंढरी', vol: '1', pn: '309' },
    { eng: 'nam tyache god', hin: 'नाम त्याचे गोड', vol: '1', pn: '311' },
    { eng: 'pandharapurachya panduranga pavan tav', hin: 'पंढरपुरच्या पांडूरंगा पावन तव', vol: '1', pn: '312' },
    { eng: 'he chakrapani tu narayan', hin: 'हे चक्रपाणी तू नारायण', vol: '1', pn: '313' },
    { eng: 'dumadumale aj pandharapur', hin: 'दुमदुमले आज पंढरपूर', vol: '1', pn: '314' },
    { eng: 'pandhari rajadhani ya jagachi', hin: 'पंढरी राजधानी या जगाची', vol: '1', pn: '315' },
    { eng: 'jagevari devadhideva jaga', hin: 'जागेवरी देवाधिदेवा जागा', vol: '1', pn: '316' },
    { eng: 'jay jay viththal viththal rakhumai', hin: 'जय जय विठ्ठल विठ्ठल रखुमाई', vol: '1', pn: '317' },
    { eng: 'chandrabhage tati rakhumai', hin: 'चंद्रभागे तटी रखुमाई', vol: '1', pn: '318' },
    { eng: 'chandrabhaga pandharit', hin: 'चंद्रभागा पंढरीत', vol: '1', pn: '319' },
    { eng: 'viththal viththal anande gau', hin: 'विठ्ठल विठ्ठल आनंदे गाऊ', vol: '1', pn: '320' },
    { eng: 'sakha hari majha pandharapura', hin: 'सखा हरि माझा पंढरपूरा', vol: '1', pn: '321' },
    { eng: 'vithu majha jagojagi', hin: 'विठू माझा जागोजागी', vol: '1', pn: '322' },
    { eng: 'pandurang pandurang garibacha dev', hin: 'पांडुरंग पांडुरंग गरिबाचा देव', vol: '1', pn: '323' },
    { eng: 'sheshavar dharati dharativar vit', hin: 'शेषावर धरती धरतीवर वीट', vol: '1', pn: '324' },
    { eng: 'majha viththal haravala koni pahile ka', hin: 'माझा विठ्ठल हरवला कोणी पाहिले का', vol: '1', pn: '325' },
    { eng: 'pandhari varituni valuya vatevari', hin: 'पंढरी वारीतूनी चालुया वाटेवरी', vol: '1', pn: '328' },
    { eng: 'jay jay ramakrshn hari', hin: 'जय जय रामकृष्ण हरी', vol: '1', pn: '329' },
    { eng: 'paha chandrabhaga kath pandharicha that', hin: 'पाहा चंद्रभागा काठ पंढरीवा थाट', vol: '1', pn: '330' },
    { eng: 'ajakal jo to far pandharila dhavato', hin: 'आजकाल जो तो फार पंढरीला धावतो', vol: '1', pn: '331' },
    { eng: 'ubha to vite pandurang', hin: 'उभा तो विटे पांडुरंग', vol: '1', pn: '332' },
    { eng: 'ubha vitevar ase kon pahu', hin: 'उभा विटेवर असे कोण पाहू', vol: '1', pn: '333' },
    { eng: 'chandrabhaga vahate jyachya dwari', hin: 'चंद्रभागा वाहते ज्याच्या द्वारी', vol: '1', pn: '334' },
    { eng: 'pragatashi viththala premapoti', hin: 'प्रगटशी विठ्ठला प्रेमापोटी', vol: '1', pn: '336' },
    { eng: 'jagojagi pandurang bhakt gati', hin: 'जागोजागी पांडुरंग भक्त गाती', vol: '1', pn: '338' },
    { eng: 'panduranga tujhi lagalise odh', hin: 'पांडुरंगा तुझी लागलीसे ओढ', vol: '1', pn: '339' },
    { eng: 'pavan jhali pandhari', hin: 'पावन झाली पंढरी', vol: '1', pn: '340' },
    { eng: 'viththala viththala viththala rukminichya vara', hin: 'विठ्ठला विठ्ठला विठ्ठला रुक्मिणीच्या वरा', vol: '1', pn: '341' },
    { eng: 'nachaya lagalay dev majha pandhariraya', hin: 'नाचाया लागलाय देव माझा पंढरीराया', vol: '1', pn: '342' },
    { eng: 'vithu ubha vitevar pahila', hin: 'विठू उभा विटेवर पाहिला', vol: '1', pn: '343' },
    { eng: 'mhane jauya pandharapuri gatase tuka', hin: 'म्हणे जाऊया पंढरपूरी गातसे तुका', vol: '1', pn: '344' },
    { eng: 'chandrabhagetati vitevarati jagajethi', hin: 'चंद्रभागेतटी विटेवरती जगजेठी', vol: '1', pn: '345' },
    { eng: 'bramh ujavikade shiv davikade', hin: 'ब्रह्म उजवीकडे शीव डावीकडे', vol: '1', pn: '346' },
    { eng: 'chandrabhage tati thambelase vithu', hin: 'चंद्रभागे तटी थांबेलासे विठू', vol: '1', pn: '347' },
    { eng: 'antari nishidin karito aradhana', hin: 'अंतरी निशिदिन करीतो आराधना', vol: '1', pn: '348' },
    { eng: 'prapanchachya sagarat nav majhi chalavi', hin: 'प्रपंचाच्या सागरात नाव माझी चालवी', vol: '1', pn: '349' },
    { eng: 'jethe bahm har jagajethi svaye ubhe rahile', hin: 'जेथे बह्म हर जगजेठी स्वये उभे राहिले', vol: '1', pn: '350' },
    { eng: 'narayana satyanarayana', hin: 'नारायणा सत्यनारायणा', vol: '1', pn: '351' },
    { eng: 'savari sansari satyanarayana', hin: 'सावरी संसारी सत्यनारायणा', vol: '1', pn: '352' },
    { eng: 'pandharichya natha ata kshanbhar yere', hin: 'पंढरीच्या नाथा आता क्षणभर येरे', vol: '1', pn: '353' },
    { eng: 'yere lagabag lagabag yere viththala', hin: 'येरे लगबग लाबग येरे विठ्ठला', vol: '1', pn: '354' },
    { eng: 'ye jhani jara ye shridhara', hin: 'ये झणी जरा ये श्रीधरा', vol: '1', pn: '355' },
    { eng: 'raghunadana nandana karito tula vandana', hin: 'रघुनदना नंदना करीतो तुला वदना', vol: '1', pn: '356' },
    { eng: 'pandhari pandhari sasar te majha ahe', hin: 'पंढरी पंढरी सासर ते माझं आहे', vol: '1', pn: '357' },
    { eng: 'he nath narayana govind gopal radheshyam', hin: 'हे नाथ नारायणा गोविंद गोपाळ राधेश्याम', vol: '1', pn: '358' },
    { eng: 'kari sambhal nijashramat thor muni valmiki', hin: 'करी सांभाळ निजाश्रमात थोर मूनी वाल्मिकी', vol: '1', pn: '360' },
    { eng: 'vithu tuhi baghun marashi ka dadi', hin: 'विठू तुही बघून मारशी का दडी', vol: '1', pn: '361' },
    { eng: 'bola mukhe bola pandurang hari', hin: 'बोला मुखे बोला पांडुरंग हरि', vol: '1', pn: '362' },
    { eng: 'gati vrukshaveli vithuche abhang', hin: 'गाती वृक्षवेली विठूचे अभंग', vol: '1', pn: '363' },
    { eng: 'pimpalas pan panavar dhyan', hin: 'पिपळास पान पानावर ध्यान', vol: '1', pn: '364' },
    { eng: 'sati rami doghi bahini', hin: 'सती रामी दोघी बहिणी', vol: '1', pn: '365' },
    { eng: 'ranga dari lagalya darshanala', hin: 'रांगा दारी लागल्या दर्शनाला', vol: '1', pn: '366' },
    { eng: 'pandurang bol pandurang bol name tyache anamol', hin: 'पांडुरंग बोल पांडुरंग बोल नामे त्याचे अनमोल', vol: '1', pn: '367' },
    { eng: 'ram patit pavan patit pavan ram', hin: 'राम पतित पावन पतित पावन राम', vol: '1', pn: '368' },
    { eng: 'yugeyuge rahi chakrapani ubha vitevari', hin: 'युगेयुगे राही चक्रपाणी उभा विटेवरी', vol: '1', pn: '369' },
    { eng: 'chandrabhaget bhijale ang ang', hin: 'चंद्रभागेत भिजले अंग अंग', vol: '1', pn: '370' },
    { eng: 'kuni pahila ka keshavala madhavala', hin: 'कुणी पाहिला का केशवाला माधवाला', vol: '1', pn: '371' },
    { eng: 'lagbag ye kanha tujavin chain muli', hin: 'लगबग ये कान्हा तुजविण चैन मुळी', vol: '1', pn: '372' },
    { eng: 'sundari radha nartan kari hari dhar adhari', hin: 'सुंदरी राधा नर्तन करी हरि धर अधरी', vol: '1', pn: '373' }
];

if (typeof module === 'object' && module.exports) {
    module.exports = p1;
}
